import { useEffect, useRef, useState } from "react";
import { Search, X } from "lucide-react";
import { api } from "../lib/api";
import { useAppStore } from "../store/useAppStore";
import { useNavigate } from "react-router-dom";

export function GlobalSearch(){
  const mode=useAppStore(s=>s.mode);const[open,setOpen]=useState(false);const[q,setQ]=useState("");const[result,setResult]=useState<any>({funds:[],managers:[],securities:[]});const[recents,setRecents]=useState<any[]>([]);const[loading,setLoading]=useState(false);const input=useRef<HTMLInputElement>(null);const navigate=useNavigate();
  useEffect(()=>{const show=()=>{setOpen(true);setTimeout(()=>input.current?.focus(),30)};const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();show()}if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',key);window.addEventListener('fundscope:search',show as EventListener);return()=>{window.removeEventListener('keydown',key);window.removeEventListener('fundscope:search',show as EventListener)}},[]);
  useEffect(()=>{if(open)api.recents(8).then(setRecents).catch(()=>setRecents([]))},[open]);
  useEffect(()=>{let alive=true;const timer=setTimeout(async()=>{if(!q.trim()){setResult({funds:[],managers:[],securities:[]});setLoading(false);return}setLoading(true);try{const x=await api.search(mode,q.trim(),6);if(alive)setResult(x)}catch{if(alive)setResult({funds:[],managers:[],securities:[]})}finally{if(alive)setLoading(false)}},220);return()=>{alive=false;clearTimeout(timer)}},[q,mode]);
  const go=(route:string)=>{setOpen(false);setQ('');navigate(route)};const total=(result.funds?.length||0)+(result.managers?.length||0)+(result.securities?.length||0);
  const recentMark=(x:any)=>x.entity_type==='manager'?<span className="command-avatar">{String(x.entity_name||'?').slice(0,1)}</span>:<span className="command-code">{x.entity_id}</span>;
  return <><button className="command-trigger" onClick={()=>{setOpen(true);setTimeout(()=>input.current?.focus(),30)}}><Search size={16}/><span>搜索基金、基金经理或证券</span><kbd>Ctrl K</kbd></button>{open&&<div className="command-backdrop" onMouseDown={()=>setOpen(false)}><div className="command-palette" onMouseDown={e=>e.stopPropagation()}><div className="command-input-row"><Search size={18}/><input ref={input} value={q} onChange={e=>setQ(e.target.value)} placeholder="输入基金代码、名称、经理或证券"/><span className={`command-searching ${loading?'show':''}`}>搜索中</span><button onClick={()=>setOpen(false)} aria-label="关闭"><X size={17}/></button></div><div className="command-results">{!q&&recents.length>0&&<div className="command-group"><div className="command-group-title">最近研究</div>{recents.map(x=><button key={`${x.entity_type}-${x.entity_id}`} onClick={()=>go(x.route||'/workspace')}>{recentMark(x)}<span className="command-main"><b>{x.entity_name}</b><small>{x.entity_type==='fund'?'基金':x.entity_type==='manager'?'基金经理':'证券'}</small></span></button>)}</div>}{!q&&recents.length===0&&<div className="command-empty"><b>输入代码或名称开始搜索</b><span>支持基金、基金经理和证券</span></div>}{q&&!loading&&total===0&&<div className="command-empty"><b>没有找到结果</b><span>可尝试更短的名称或证券代码</span></div>}{result.funds?.length>0&&<div className="command-group"><div className="command-group-title">基金</div>{result.funds.map((f:any)=><button key={f.fund_code} onClick={()=>go(`/funds?code=${encodeURIComponent(f.fund_code)}`)}><span className="command-code">{f.fund_code}</span><span className="command-main"><b>{f.fund_name}</b><small>{f.fund_type||'未分类'}</small></span></button>)}</div>}{result.managers?.length>0&&<div className="command-group"><div className="command-group-title">基金经理</div>{result.managers.map((m:any)=><button key={`${m.manager_name}-${m.company}`} onClick={()=>go(`/managers?mid=${encodeURIComponent(m.manager_id||'')}`)}><span className="command-avatar">{String(m.manager_name||'?').slice(0,1)}</span><span className="command-main"><b>{m.manager_name}</b><small>{m.company||'—'}</small></span></button>)}</div>}{result.securities?.length>0&&<div className="command-group"><div className="command-group-title">证券</div>{result.securities.map((s:any)=><button key={s.stock_code} onClick={()=>go(`/explorer?security=${encodeURIComponent(s.stock_code)}`)}><span className="command-code">{s.stock_code}</span><span className="command-main"><b>{s.stock_name}</b><small>{s.sector||'未分类'}</small></span></button>)}</div>}</div></div></div>}</>;
}
