import { useEffect,useMemo,useRef,useState } from "react";
import { Check,ChevronDown,Search } from "lucide-react";
import { api } from "../lib/api";
import { useAppStore } from "../store/useAppStore";

export function FundPicker({value,onChange,label}:{value:string;onChange:(code:string)=>void;label?:string}){
 const mode=useAppStore(s=>s.mode);const[open,setOpen]=useState(false);const[q,setQ]=useState('');const[items,setItems]=useState<any[]>([]);const[selected,setSelected]=useState<any>(null);const box=useRef<HTMLDivElement>(null);
 useEffect(()=>{api.funds(mode,q).then(setItems).catch(()=>setItems([]))},[mode,q]);useEffect(()=>{if(value)api.funds(mode,value).then(xs=>setSelected(xs.find(x=>String(x.fund_code)===String(value))||xs[0]||null)).catch(()=>{})},[value,mode]);useEffect(()=>{const fn=(e:MouseEvent)=>{if(box.current&&!box.current.contains(e.target as Node))setOpen(false)};document.addEventListener('mousedown',fn);return()=>document.removeEventListener('mousedown',fn)},[]);
 return <div className="remote-picker" ref={box}><button className="remote-picker-trigger" onClick={()=>setOpen(v=>!v)}><span>{selected?`${selected.fund_code} · ${selected.fund_name}`:(label||'选择基金')}</span><ChevronDown size={15}/></button>{open&&<div className="remote-picker-popover"><div className="remote-picker-search"><Search size={15}/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索基金代码或名称"/></div><div className="remote-picker-list">{items.map(x=><button key={x.fund_code} onClick={()=>{onChange(String(x.fund_code));setSelected(x);setOpen(false);setQ('')}}><span className="picker-code">{x.fund_code}</span><span className="picker-name"><b>{x.fund_name}</b><small>{x.fund_type||'未分类'}</small></span>{String(x.fund_code)===String(value)&&<Check size={15}/>}</button>)}</div></div>}</div>
}

const LETTERS='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
export function ManagerPicker({value,onChange}:{value:string;onChange:(item:any)=>void}){
 const mode=useAppStore(s=>s.mode);const[open,setOpen]=useState(false);const[q,setQ]=useState('');const[items,setItems]=useState<any[]>([]);const[tab,setTab]=useState<'surname'|'company'>('surname');const[letter,setLetter]=useState('C');const[company,setCompany]=useState('');const box=useRef<HTMLDivElement>(null);
 useEffect(()=>{api.managerCatalog(mode).then(xs=>{setItems(xs);if(xs.length&&!value){setLetter(xs[0].surname_initial||'C')}}).catch(()=>setItems([]))},[mode]);useEffect(()=>{const fn=(e:MouseEvent)=>{if(box.current&&!box.current.contains(e.target as Node))setOpen(false)};document.addEventListener('mousedown',fn);return()=>document.removeEventListener('mousedown',fn)},[]);
 const selected=items.find(x=>x.manager_id===value);useEffect(()=>{if(selected?.surname_initial)setLetter(selected.surname_initial);if(selected?.company)setCompany(selected.company)},[value,items.length]);const filtered=useMemo(()=>{if(!q.trim())return items;const n=q.trim().toLowerCase();return items.filter(x=>String(x.manager_name).toLowerCase().includes(n)||String(x.company||'').toLowerCase().includes(n))},[items,q]);
 const companies=useMemo(()=>[...new Set(items.map(x=>x.company).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'zh-CN')),[items]);useEffect(()=>{if(!company&&companies[0])setCompany(companies[0])},[companies]);
 const choose=(x:any)=>{onChange(x);setOpen(false);setQ('')};
 const letterItems=filtered.filter(x=>(x.surname_initial||'#')===letter);const companyItems=filtered.filter(x=>x.company===company);
 return <div className="remote-picker manager-picker" ref={box}><button className="remote-picker-trigger" onClick={()=>setOpen(v=>!v)}><span>{selected?`${selected.manager_name} · ${selected.company}`:'选择基金经理'}</span><ChevronDown size={15}/></button>{open&&<div className="remote-picker-popover manager-popover">
   <div className="remote-picker-search"><Search size={15}/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索基金经理或基金公司"/></div>
   <div className="manager-tabs"><button className={tab==='surname'?'active':''} onClick={()=>setTab('surname')}>按姓氏</button><button className={tab==='company'?'active':''} onClick={()=>setTab('company')}>按基金公司</button></div>
   {q.trim()?<div className="remote-picker-list manager-results">{filtered.slice(0,100).map(x=><button key={x.manager_id} onClick={()=>choose(x)}><span className="picker-avatar">{String(x.manager_name||'?').slice(0,1)}</span><span className="picker-name"><b>{x.manager_name}</b><small>{x.company||'—'}</small></span>{x.manager_id===value&&<Check size={15}/>}</button>)}</div>:
   tab==='surname'?<div className="manager-directory"><div className="letter-index">{LETTERS.map(l=><button key={l} className={l===letter?'active':''} onClick={()=>setLetter(l)}>{l}</button>)}</div><div className="manager-group"><div className="manager-group-title">{letter} · 姓氏拼音</div><div className="remote-picker-list">{letterItems.map(x=><button key={x.manager_id} onClick={()=>choose(x)}><span className="picker-avatar">{String(x.manager_name||'?').slice(0,1)}</span><span className="picker-name"><b>{x.manager_name}</b><small>{x.company||'—'}</small></span>{x.manager_id===value&&<Check size={15}/>}</button>)}</div></div></div>:
   <div className="company-directory"><div className="company-list">{companies.map(c=><button key={c} className={c===company?'active':''} onClick={()=>setCompany(c)}>{c}</button>)}</div><div className="manager-group"><div className="manager-group-title">{company||'基金公司'}</div><div className="remote-picker-list">{companyItems.map(x=><button key={x.manager_id} onClick={()=>choose(x)}><span className="picker-avatar">{String(x.manager_name||'?').slice(0,1)}</span><span className="picker-name"><b>{x.manager_name}</b><small>{x.company||'—'}</small></span>{x.manager_id===value&&<Check size={15}/>}</button>)}</div></div></div>}
 </div>}</div>
}
