import { useEffect,useMemo,useState } from "react";
import type { ColumnDef } from "@tanstack/react-table";
import { AlertTriangle,CheckCircle2,Database,FolderOpen,Layers3,Pause,Play,ShieldCheck,Square,Users } from "lucide-react";
import { api } from "../lib/api";
import { PageHeader } from "../components/PageHeader";
import { MetricStrip } from "../components/MetricStrip";
import { Panel } from "../components/Panel";
import { DataTable } from "../components/DataTable";
import { TaskProgressButton } from "../components/TaskProgress";
import { EmptyState } from "../components/Loading";
import { useAppStore } from "../store/useAppStore";
import { formatNumber } from "../lib/format";

const nowYear=new Date().getFullYear();
const YEAR_OPTIONS=Array.from({length:nowYear-1997},(_,i)=>1998+i);
function Choice({items,value,onChange}:{items:Array<{value:string;label:string}>;value:string;onChange:(v:string)=>void}){return <div className="choice-row">{items.map(x=><button key={x.value} className={x.value===value?'active':''} onClick={()=>onChange(x.value)}>{x.label}</button>)}</div>}
function Badge({status}:{status:string}){const map:any={success:['完成','good'],running:['进行中','info'],paused:['已暂停','muted'],cooling:['冷却中','warning'],queued:['等待','info'],error:['失败','bad'],cancelled:['取消','muted'],interrupted:['中断','bad']};const x=map[status]||[status,'muted'];return <span className={`status-badge ${x[1]}`}>{x[0]}</span>}

export function DataCenterPage(){
 const role=useAppStore(s=>s.role);const mode=useAppStore(s=>s.mode);const setMode=useAppStore(s=>s.setMode);
 const[health,setHealth]=useState<any>(null);const[tasks,setTasks]=useState<any[]>([]);const[profiles,setProfiles]=useState<any[]>([]);const[quality,setQuality]=useState<any>(null);const[snapshots,setSnapshots]=useState<any[]>([]);const[storage,setStorage]=useState<any>(null);const[tab,setTab]=useState<'tasks'|'quality'|'snapshots'|'storage'>('tasks');const[notice,setNotice]=useState('');
 const[strategy,setStrategy]=useState(()=>localStorage.getItem('fundscope_collection_strategy')||'standard');const[yearMode,setYearMode]=useState('2');const[startYear,setStartYear]=useState(nowYear-4);const[endYear,setEndYear]=useState(nowYear);const[quarterMode,setQuarterMode]=useState('8');const[customQuarters,setCustomQuarters]=useState(8);const[scope,setScope]=useState('300');const[customLimit,setCustomLimit]=useState(300);const[confirmAll,setConfirmAll]=useState(false);const[force,setForce]=useState(false);const[securityScope,setSecurityScope]=useState('all');const[securityDepth,setSecurityDepth]=useState('fast');const[plan,setPlan]=useState<any>(null);
 const refresh=async()=>{const[h,t]=await Promise.all([api.health(),api.tasks(50)]);setHealth(h);setTasks(t)};
 useEffect(()=>{localStorage.setItem('fundscope_collection_strategy',strategy)},[strategy]);
 useEffect(()=>{api.collectionProfiles().then(setProfiles).catch(()=>setProfiles([]))},[]);
 useEffect(()=>{
   let stopped=false;let timer:any=null;
   const tick=async()=>{try{const t=await api.tasks(50);if(stopped)return;setTasks(t);const active=t.some((x:any)=>['queued','running','paused','cooling'].includes(String(x.status)));const delay=document.hidden?30000:(active?2500:15000);timer=setTimeout(tick,delay)}catch{timer=setTimeout(tick,8000)}};
   tick();
   const onUpdate=()=>{if(timer)clearTimeout(timer);tick()};window.addEventListener('fundscope-task-updated',onUpdate);
   return()=>{stopped=true;if(timer)clearTimeout(timer);window.removeEventListener('fundscope-task-updated',onUpdate)}
 },[]);
 useEffect(()=>{let stopped=false;let timer:any=null;const tick=async()=>{try{const h=await api.health();if(!stopped){setHealth(h);if(mode==='demo'&&Number(h?.holdings||0)>0)setMode('local')}}catch{/* 后端暂不可用时保留当前状态 */}finally{if(!stopped)timer=setTimeout(tick,20000)}};tick();return()=>{stopped=true;if(timer)clearTimeout(timer)}},[mode,setMode]);
 useEffect(()=>{if(tab==='quality')api.quality().then(setQuality);if(tab==='snapshots')api.snapshots().then(setSnapshots);if(tab==='storage')api.storage().then(setStorage)},[tab,tasks.length]);
 const sinceInception=yearMode==='since';
 const selectedYears=useMemo(()=>{if(sinceInception)return[];if(yearMode==='custom')return YEAR_OPTIONS.filter(y=>y>=Math.min(startYear,endYear)&&y<=Math.max(startYear,endYear));return Array.from({length:Number(yearMode)},(_,i)=>nowYear-i).sort()},[yearMode,startYear,endYear]);
 const selectedQuarters=quarterMode==='custom'?customQuarters:Number(quarterMode);const selectedLimit=scope==='all'?null:scope==='custom'?customLimit:Number(scope);const latest=(type:string)=>tasks.find(t=>t.task_type===type);const strategyMeta:any=profiles.find((x:any)=>x.value===strategy)||{holdings:4,market:3,security_master:8,return_gap:5};const strategyItems=(profiles.length?profiles:[{value:'safe',label:'稳健'},{value:'standard',label:'标准'},{value:'fast',label:'极速'}]).map((x:any)=>({value:x.value,label:x.label}));
 const start=async(fn:()=>Promise<any>)=>{try{setNotice('');await fn();await refresh()}catch(e:any){setNotice(e?.message||'任务未启动')}};
 useEffect(()=>{if(tab!=='tasks')return;const id=setTimeout(()=>{api.holdingsPlan(selectedYears,selectedLimit,force,sinceInception,null).then(setPlan).catch(()=>setPlan(null))},180);return()=>clearTimeout(id)},[tab,yearMode,startYear,endYear,scope,customLimit,force]);
 const taskAction=async(t:any,action:'pause'|'resume'|'cancel')=>{try{if(action==='pause')await api.pauseTask(t.task_id);else if(action==='resume')await api.resumeTask(t.task_id);else await api.cancelTask(t.task_id);setTasks(await api.tasks(50))}catch(e:any){setNotice(e?.message||'操作未完成')}};
 const taskCols:ColumnDef<any>[]=[{accessorKey:'task_type',header:'任务',cell:({getValue})=>({funds:'基金代码',managers:'基金经理',fund_master:'基金主体',market:'市场报告',holdings:'季度持仓',security_master:'证券主表',return_gap:'分析数据',major_changes:'重大变动',incremental:'日常增量'} as any)[String(getValue())]||String(getValue())},{accessorKey:'status',header:'状态',cell:({getValue})=><Badge status={String(getValue())}/>},{accessorKey:'progress',header:'进度',cell:({getValue})=><span className="num">{Math.round(Number(getValue()||0))}%</span>},{accessorKey:'message',header:'任务状态',cell:({getValue,row})=><span className={row.original.status==='cooling'?'cooling-text':''}>{String(getValue()||'—')}</span>},{accessorKey:'created_at',header:'时间'},{id:'actions',header:'操作',cell:({row})=>{const t=row.original;const st=String(t.status);if(!['queued','running','paused','cooling'].includes(st))return <span>—</span>;return <div className="task-row-actions">{(st==='running'||st==='cooling')&&<button title="暂停" onClick={()=>taskAction(t,'pause')}><Pause size={13}/></button>}{st==='paused'&&<button title="继续" onClick={()=>taskAction(t,'resume')}><Play size={13}/></button>}<button className="cancel" title="取消" onClick={()=>taskAction(t,'cancel')}><Square size={12}/></button></div>}}];
 const errorCols:ColumnDef<any>[]=[{accessorKey:'fund_code',header:'基金代码'},{accessorKey:'requested_year',header:'年份'},{accessorKey:'error_type',header:'类型'},{accessorKey:'error',header:'详情'},{accessorKey:'updated_at',header:'时间'}];
 const fm=health?.fund_master||{};
 const rangeLabel=sinceInception?'成立至今':yearMode==='custom'?`${Math.min(startYear,endYear)}–${Math.max(startYear,endYear)}`:`最近 ${yearMode} 年`;
 if(role==='analyst')return <><PageHeader eyebrow="数据管理" title="数据中心"/><EmptyState title="当前角色仅开放研究权限" body="以维护角色启动 FundScope 后可执行采集、导入和快照操作。"/></>;
 return <><PageHeader eyebrow="数据管理" title="数据中心"/>
 <MetricStrip items={[{label:'基金份额',value:(health?.funds||0).toLocaleString(),sub:fm.masters?`${Number(fm.masters).toLocaleString()} 个基金主体`:'—'},{label:'主动偏股池',value:(fm.eligible||0).toLocaleString(),sub:fm.duplicate_shares?`已合并 ${Number(fm.duplicate_shares).toLocaleString()} 个重复份额`:''},{label:'持仓覆盖',value:health?`${Number(health.holding_funds||0).toLocaleString()} 只`:'—',sub:health?`${formatNumber(health.holding_coverage_pct)}%`:''},{label:'证券主表',value:(health?.security_master||0).toLocaleString(),sub:health?.security_industry?`${Number(health.security_industry).toLocaleString()} 已映射行业`:'—'}]}/>
 <div className="data-tabs"><button className={tab==='tasks'?'active':''} onClick={()=>setTab('tasks')}>采集任务</button><button className={tab==='quality'?'active':''} onClick={()=>setTab('quality')}>数据质量</button><button className={tab==='snapshots'?'active':''} onClick={()=>setTab('snapshots')}>数据快照</button><button className={tab==='storage'?'active':''} onClick={()=>setTab('storage')}>数据位置</button></div>
 {notice&&<div className="notice error"><AlertTriangle size={15}/><b>{notice}</b></div>}
 {tab==='tasks'&&<>
  <div className="collector-toolbar"><div><span>采集模式</span><Choice value={strategy} onChange={setStrategy} items={strategyItems}/><div className="collection-policy-note"><span>持仓 <b>{strategyMeta.holdings}</b> 路</span><span>市场 <b>{strategyMeta.market}</b> 路</span><span>证券主表 <b>{strategyMeta.security_master}</b> 路</span><span>分析数据 <b>{strategyMeta.return_gap}</b> 路</span></div></div><div className="incremental-action"><span>日常维护</span><TaskProgressButton task={latest('incremental')} idleLabel="增量更新" onClick={()=>start(()=>api.startIncremental(strategy))}/></div></div>

  <div className="grid two-equal data-grid"><Panel title="基础资料"><div className="operation-list compact"><div><Database size={18}/><div><b>基金代码</b><span>{health?.funds?`${Number(health.funds).toLocaleString()} 条`:'—'}</span></div><TaskProgressButton task={latest('funds')} idleLabel="更新" onClick={()=>start(api.startFunds)}/></div><div><Users size={18}/><div><b>基金经理</b><span>{health?.managers?`${Number(health.managers).toLocaleString()} 条`:'—'}</span></div><TaskProgressButton task={latest('managers')} idleLabel="更新" onClick={()=>start(api.startManagers)}/></div><div><Layers3 size={18}/><div><b>基金主体</b><span>{fm.masters?`${Number(fm.masters).toLocaleString()} 个 · ${Number(fm.eligible||0).toLocaleString()} 个主动偏股`:'—'}</span></div><TaskProgressButton task={latest('fund_master')} idleLabel="重建" onClick={()=>start(api.startFundMaster)}/></div></div></Panel>
  <Panel title="市场报告"><div className="setting-block"><Choice value={quarterMode} onChange={setQuarterMode} items={[{value:'4',label:'4 季度'},{value:'8',label:'8 季度'},{value:'12',label:'12 季度'},{value:'16',label:'16 季度'},{value:'custom',label:'自定义'}]}/>{quarterMode==='custom'&&<div className="custom-line"><select value={customQuarters} onChange={e=>setCustomQuarters(Number(e.target.value))}>{Array.from({length:17},(_,i)=>i+4).map(v=><option key={v} value={v}>{v} 季度</option>)}</select></div>}<div className="action-row"><span>{health?.latest_market_period||'—'}</span><TaskProgressButton task={latest('market')} idleLabel="更新市场" onClick={()=>start(()=>api.startMarket(selectedQuarters,force,strategy) )}/></div></div></Panel></div>

  <Panel title="基金季度持仓"><div className="collector-layout v8"><div className="setting-block"><label>历史范围</label><Choice value={yearMode} onChange={setYearMode} items={[{value:'1',label:'最近 1 年'},{value:'2',label:'最近 2 年'},{value:'3',label:'最近 3 年'},{value:'5',label:'最近 5 年'},{value:'since',label:'成立至今'},{value:'custom',label:'自定义'}]}/>{yearMode==='custom'&&<div className="range-select"><select value={startYear} onChange={e=>setStartYear(Number(e.target.value))}>{YEAR_OPTIONS.map(y=><option key={y} value={y}>{y}</option>)}</select><span>至</span><select value={endYear} onChange={e=>setEndYear(Number(e.target.value))}>{YEAR_OPTIONS.map(y=><option key={y} value={y}>{y}</option>)}</select></div>}</div><div className="setting-block"><label>基金主体范围</label><Choice value={scope} onChange={setScope} items={[{value:'100',label:'100 个'},{value:'300',label:'300 个'},{value:'1000',label:'1000 个'},{value:'all',label:'全部'},{value:'custom',label:'自定义'}]}/>{scope==='custom'&&<div className="custom-line"><input type="number" min={1} value={customLimit} onChange={e=>setCustomLimit(Math.max(1,Number(e.target.value)))}/><span>个</span></div>}</div><div className="setting-block"><label>缓存策略</label><Choice value={force?'refresh':'missing'} onChange={v=>setForce(v==='refresh')} items={[{value:'missing',label:'仅补缺失'},{value:'refresh',label:'刷新已有'}]}/></div></div>
  <div className="collection-plan"><div><span>范围</span><b>{rangeLabel}</b></div><div><span>基金主体</span><b>{plan?.selected_masters??'—'}</b></div><div><span>{sinceInception?'已知年度请求':'预计年度请求'}</span><b>{plan?.planned_year_requests??'—'}</b></div><div><span>缓存年度</span><b>{plan?.cached_years??'—'}</b></div>{sinceInception&&<div><span>成立日待补</span><b>{plan?.unknown_inception??'—'}</b></div>}</div>
  <div className="collector-footer">{scope==='all'&&<label className="all-confirm"><input type="checkbox" checked={confirmAll} onChange={e=>setConfirmAll(e.target.checked)}/><span>确认全量</span></label>}<TaskProgressButton task={latest('holdings')} idleLabel="开始采集" disabled={(scope==='all'&&!confirmAll)||(!sinceInception&&selectedYears.length===0)} onClick={()=>start(()=>api.startHoldings(selectedYears,selectedLimit,strategy,force,sinceInception,null))}/></div></Panel>

  <div className="grid two-equal"><Panel title="证券主表"><div className="setting-block"><label>范围</label><Choice value={securityScope} onChange={setSecurityScope} items={[{value:'300',label:'300 只'},{value:'1000',label:'1000 只'},{value:'all',label:'全部持仓证券'}]}/></div><div className="setting-block divide-top"><label>补齐层级</label><Choice value={securityDepth} onChange={setSecurityDepth} items={[{value:'fast',label:'快速主表'},{value:'deep',label:'深度补齐'}]}/></div><div className="action-row"><span>{health?.security_master?`${Number(health.security_master).toLocaleString()} 条`:'—'}</span><TaskProgressButton task={latest('security_master')} idleLabel={securityDepth==='deep'?'深度补齐':'更新主表'} onClick={()=>start(()=>api.startSecurityMaster(securityScope==='all'?null:Number(securityScope),strategy,securityDepth==='deep'))}/></div></Panel>
  <Panel title="数据库"><label className="dropzone minimal"><Database size={22}/><b>导入数据库</b><input type="file" accept=".db,.sqlite,.sqlite3" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{await api.importDb(file);setNotice('导入完成');await refresh()}catch(err:any){setNotice(err?.message||'导入失败')}}}/></label></Panel></div>
  <Panel title="最近任务"><DataTable data={tasks} columns={taskCols} maxHeight={330}/></Panel>
 </>}
 {tab==='quality'&&<>{!quality?<div className="quality-loading">检查中…</div>:<><div className="quality-hero"><div className="quality-score"><span>综合质量</span><b>{formatNumber(quality.score)}</b><small>/ 100</small></div><div><span>基金主体覆盖</span><b>{formatNumber(quality.coverage_pct)}%</b><small>{quality.covered_funds} / {quality.applicable_funds}</small></div><div><span>空结果</span><b>{quality.empty}</b><small>来源返回空记录</small></div><div><span>错误任务</span><b className={quality.errors?'bad-text':''}>{quality.errors}</b><small>需检查</small></div></div>
  <div className="grid two-equal"><Panel title="关键字段完整度"><div className="quality-bars">{quality.tables.map((x:any)=><div key={x.table}><div><b>{x.label}</b><span>{formatNumber(x.completeness_pct)}%</span></div><div className="quality-track"><i className={x.status} style={{width:`${x.completeness_pct}%`}}/></div><small>{Number(x.rows).toLocaleString()} 行 · 缺失 {Number(x.missing).toLocaleString()}</small></div>)}</div></Panel><Panel title="证券主表覆盖"><div className="quality-facts"><div><ShieldCheck size={17}/><span>证券数量</span><b>{quality.security.total}</b></div><div><ShieldCheck size={17}/><span>行业覆盖</span><b>{formatNumber(quality.security.industry_pct)}%</b></div><div><ShieldCheck size={17}/><span>市值覆盖</span><b>{formatNumber(quality.security.market_cap_pct)}%</b></div><div><ShieldCheck size={17}/><span>估值覆盖</span><b>{formatNumber(quality.security.valuation_pct)}%</b></div><div><ShieldCheck size={17}/><span>成长覆盖</span><b>{formatNumber(quality.security.growth_pct)}%</b></div></div></Panel></div>
  <div className="grid two-equal"><Panel title="基金主体去重"><div className="quality-facts"><div><Layers3 size={17}/><span>基金主体</span><b>{quality.fund_master.masters||0}</b></div><div><Layers3 size={17}/><span>主动偏股</span><b>{quality.fund_master.eligible||0}</b></div><div><Layers3 size={17}/><span>排除</span><b>{quality.fund_master.excluded||0}</b></div><div><Layers3 size={17}/><span>减少重复份额</span><b>{quality.fund_master.duplicate_shares||0}</b></div></div></Panel><Panel title="异常检查"><div className="quality-facts"><div><ShieldCheck size={17}/><span>异常权重</span><b>{quality.invalid_weight}</b></div><div><ShieldCheck size={17}/><span>重复记录</span><b>{quality.duplicate_keys}</b></div><div><ShieldCheck size={17}/><span>采集错误</span><b>{quality.errors}</b></div><div><ShieldCheck size={17}/><span>空结果</span><b>{quality.empty}</b></div></div></Panel></div>
  <Panel title="年度覆盖"><div className="coverage-chips">{quality.years.map((x:any)=><div key={x.year}><b>{x.year}</b><span>{Number(x.funds).toLocaleString()} 只</span><small>{Number(x.rows).toLocaleString()} 条</small></div>)}</div></Panel><Panel title="错误明细">{quality.recent_errors.length?<DataTable data={quality.recent_errors} columns={errorCols} maxHeight={360}/>:<div className="quality-empty"><CheckCircle2 size={20}/><b>无错误记录</b></div>}</Panel></>}</>}
 {tab==='snapshots'&&<><div className="snapshot-toolbar"><div><b>数据快照</b></div><button onClick={async()=>{await api.createSnapshot();setSnapshots(await api.snapshots())}}>创建快照</button></div><div className="snapshot-list">{snapshots.length?snapshots.map(s=><div key={s.name}><Database size={18}/><div><b>{s.name}</b><span>{s.created_at} · {s.size_mb} MB</span></div><button onClick={async()=>{if(confirm('恢复该快照？')){await api.restoreSnapshot(s.name);await refresh()}}}>恢复</button></div>):<div className="quality-empty">—</div>}</div></>}
 {tab==='storage'&&<>{!storage?<div className="quality-loading">读取中…</div>:<div className="storage-card"><div><span>数据库</span><b>{storage.db_path}</b><small>{storage.db_size_mb} MB</small></div><div><span>快照目录</span><b>{storage.snapshot_dir}</b></div><button onClick={()=>api.openDataFolder()}><FolderOpen size={16}/>打开目录</button></div>}</>}
 </>;
}
