import { useEffect,useMemo,useState } from "react";
import { useNavigate,useSearchParams } from "react-router-dom";
import type { ColumnDef } from "@tanstack/react-table";
import { api } from "../lib/api";
import { useAppStore } from "../store/useAppStore";
import { PageHeader } from "../components/PageHeader";
import { MetricStrip } from "../components/MetricStrip";
import { QuarterRail } from "../components/QuarterRail";
import { Panel } from "../components/Panel";
import { Chart } from "../components/Chart";
import { DataTable } from "../components/DataTable";
import { Loading,EmptyState,ErrorState } from "../components/Loading";
import { FundPicker } from "../components/RemotePicker";
import { TaskProgressButton } from "../components/TaskProgress";
import { SankeyChart } from "../components/SankeyChart";
import { RebalanceBoard,MajorChangeBoard } from "../components/RebalanceBoard";
import { categoryGrid } from "../lib/chartUtils";
import { SaveEntityButton } from "../components/SaveEntityButton";
import { MonitorRuleButton } from "../components/MonitorRuleDialog";
import { DataContext } from "../components/DataContext";
import { comparableSnapshots } from "../lib/research";
import { formatNumber } from "../lib/format";

const fmt=(v:any,d=2)=>v==null||Number.isNaN(Number(v))?'—':Number(v).toFixed(d);

const migrationSankey=(activity:any[],sectorMapped:boolean)=>{
 const grouped=new Map<string,number>();
 for(const x of activity||[]){const name=sectorMapped?(x.sector||'未分类'):(x.stock_name||x.stock_code||'未知');grouped.set(name,(grouped.get(name)||0)+Number(x.delta||0))}
 const rows=[...grouped].map(([name,delta])=>({name,delta})).filter(x=>Math.abs(x.delta)>.05);
 const neg=rows.filter(x=>x.delta<0).sort((a,b)=>a.delta-b.delta).slice(0,8);const pos=rows.filter(x=>x.delta>0).sort((a,b)=>b.delta-a.delta).slice(0,8);
 if(!neg.length||!pos.length)return{nodes:[],links:[]};
 const negTotal=neg.reduce((s,x)=>s+Math.abs(x.delta),0),posTotal=pos.reduce((s,x)=>s+x.delta,0),mass=Math.min(negTotal,posTotal);
 const nodes=[...neg.map(x=>({name:`${x.name} · 减`,side:'source'})),...pos.map(x=>({name:`${x.name} · 增`,side:'target'}))];const links:any[]=[];
 for(const a of neg)for(const b of pos){const value=mass*(Math.abs(a.delta)/negTotal)*(b.delta/posTotal);if(value>=.03)links.push({source:`${a.name} · 减`,target:`${b.name} · 增`,value:Number(value.toFixed(2))})}
 return{nodes,links:links.sort((a,b)=>b.value-a.value).slice(0,24)};
};

export function FundsPage(){
 const navigate=useNavigate();
 const mode=useAppStore(s=>s.mode);const[params,setParams]=useSearchParams();const wantedCode=params.get('code')||'';const[code,setCode]=useState(wantedCode);const[data,setData]=useState<any>(null);const[advanced,setAdvanced]=useState<any>(null);const[advancedError,setAdvancedError]=useState('');const[profile,setProfile]=useState<any>(null);const[majorChanges,setMajorChanges]=useState<any[]>([]);const[peers,setPeers]=useState<any>(null);const[peersError,setPeersError]=useState('');const[selectedPeerCode,setSelectedPeerCode]=useState('');const[peerLens,setPeerLens]=useState<any>(null);const[peerLensError,setPeerLensError]=useState('');const[peerUniverse,setPeerUniverse]=useState('all');const[quarter,setQuarter]=useState('');const[tab,setTab]=useState<'overview'|'evolution'|'advanced'|'positioning'|'peers'|'holdings'>('overview');const[error,setError]=useState('');const[gapTask,setGapTask]=useState<any>(null);const[majorTask,setMajorTask]=useState<any>(null);const[historyTask,setHistoryTask]=useState<any>(null);
 const load=async()=>{if(!code)return;setError('');try{const x=await api.fund(mode,code);setData(x);const resolvedCode=String(x.fund?.fund_code||code);const p=x.periods||[];setQuarter(q=>p.includes(q)?q:(p[p.length-1]||''));if(wantedCode!==resolvedCode)setParams({code:resolvedCode},{replace:true});api.touchRecent({entity_type:'fund',entity_id:resolvedCode,entity_name:String(x.fund?.fund_name||resolvedCode),route:`/funds?code=${encodeURIComponent(resolvedCode)}`}).catch(()=>{})}catch(e:any){setError(e?.message||String(e))}};
 useEffect(()=>{setError('');if(wantedCode){if(String(code)!==String(wantedCode))setCode(String(wantedCode));return}api.funds(mode,'').then(x=>{if(x[0])setCode(String(x[0].fund_code))}).catch((e:any)=>setError(e?.message||"请求未完成，请稍后重试"))},[mode,wantedCode]);
 useEffect(()=>{setData(null);setAdvanced(null);setAdvancedError('');setPeers(null);setPeersError('');setSelectedPeerCode('');setPeerLens(null);setPeerLensError('');load()},[code,mode]);
 useEffect(()=>{if(!code)return;let alive=true;setProfile(null);api.fundProfile(mode,code).then(x=>alive&&setProfile(x)).catch(()=>alive&&setProfile(null));return()=>{alive=false}},[code,mode]);
 useEffect(()=>{if(tab!=='peers'||!code||!quarter)return;let alive=true;setPeers(null);setPeersError('');api.fundPeers(mode,code,quarter,15).then(x=>{if(alive){setPeers(x);setSelectedPeerCode(String(x?.peers?.[0]?.fund_code||''))}}).catch((e:any)=>alive&&setPeersError(e?.message||String(e)));return()=>{alive=false}},[tab,code,mode,quarter]);
 useEffect(()=>{if(tab!=='positioning'||!code||!quarter)return;let alive=true;setPeerLens(null);setPeerLensError('');api.fundPeerLens(mode,code,quarter,peerUniverse).then(x=>alive&&setPeerLens(x)).catch((e:any)=>alive&&setPeerLensError(e?.message||String(e)));return()=>{alive=false}},[tab,code,mode,quarter,peerUniverse]);
 useEffect(()=>{if(tab!=='advanced'||!code||advanced)return;let alive=true;setAdvancedError('');api.fundAdvanced(mode,code).then(x=>alive&&setAdvanced(x)).catch((e:any)=>alive&&setAdvancedError(e?.message||String(e)));return()=>{alive=false}},[tab,code,mode,advanced]);
 useEffect(()=>{if(tab!=='evolution'||!code)return;let alive=true;api.majorChanges(mode,code).then(x=>alive&&setMajorChanges(x)).catch(()=>alive&&setMajorChanges([]));return()=>{alive=false}},[tab,code,mode]);

 useEffect(()=>{if(!gapTask||!['queued','running','paused','cooling'].includes(gapTask.status))return;const id=setInterval(async()=>{const t=await api.task(gapTask.task_id);setGapTask(t);if(t.status==='success'){api.invalidateCache(`/api/funds/${encodeURIComponent(code)}`);await load();try{setAdvanced(await api.fundAdvanced(mode,code))}catch{}}},2500);return()=>clearInterval(id)},[gapTask?.task_id,gapTask?.status,code,mode]);
 useEffect(()=>{if(!majorTask||!['queued','running','paused','cooling'].includes(majorTask.status))return;const id=setInterval(async()=>{const t=await api.task(majorTask.task_id);setMajorTask(t);if(t.status==='success'){api.invalidateCache(`/api/funds/${encodeURIComponent(code)}`);setMajorChanges(await api.majorChanges(mode,code))}},2500);return()=>clearInterval(id)},[majorTask?.task_id,majorTask?.status,code,mode]);
 useEffect(()=>{if(!historyTask||!['queued','running','paused','cooling'].includes(historyTask.status))return;const id=setInterval(async()=>{const t=await api.task(historyTask.task_id);setHistoryTask(t);if(t.status==='success'){api.invalidateCache(`/api/funds/${encodeURIComponent(code)}`);await load();setProfile(await api.fundProfile(mode,code))}},2500);return()=>clearInterval(id)},[historyTask?.task_id,historyTask?.status,code,mode]);
 const selected=useMemo(()=>data?.holdings?.filter((x:any)=>x.quarter===quarter).slice().sort((a:any,b:any)=>Number(b.weight_pct)-Number(a.weight_pct))||[],[data,quarter]);const selectedPeer=useMemo(()=>peers?.peers?.find((x:any)=>String(x.fund_code)===String(selectedPeerCode))||peers?.peers?.[0]||null,[peers,selectedPeerCode]);const periods:string[]=data?.periods||[];const idx=periods.indexOf(quarter);const previous=idx>0?periods[idx-1]:'';
 const visiblePeriods=useMemo(()=>{if(periods.length<=12)return periods;const i=Math.max(0,periods.indexOf(quarter));let start=Math.max(0,i-6);start=Math.min(start,periods.length-12);return periods.slice(start,start+12)},[data,quarter]);
 const majorYears=[...new Set([previous,quarter].filter(Boolean).map((p:string)=>Number(String(p).slice(0,4))).filter(Boolean))];
 const comparison=useMemo(()=>{if(!data||!previous||!quarter)return{oldRows:[],newRows:[],basis:'',label:''};return comparableSnapshots(data.holdings.filter((x:any)=>x.quarter===previous),data.holdings.filter((x:any)=>x.quarter===quarter),previous,quarter)},[data,quarter,previous]);
 const activity=useMemo(()=>{if(!previous||!quarter)return[];const old=new Map(comparison.oldRows.map((x:any)=>[x.stock_code,x]));const cur=new Map(comparison.newRows.map((x:any)=>[x.stock_code,x]));const keys=new Set([...old.keys(),...cur.keys()]);return [...keys].map(k=>{const a:any=old.get(k),b:any=cur.get(k);const delta=(b?.weight_pct||0)-(a?.weight_pct||0);return{stock_code:k,stock_name:b?.stock_name||a?.stock_name,sector:b?.sector||a?.sector,weight_old:a?.weight_pct??null,weight_new:b?.weight_pct??null,delta,activity:!a?'新进入披露':!b?'退出披露':delta>.05?'权重上升':delta<-.05?'权重下降':'基本稳定'}}).sort((a,b)=>b.delta-a.delta)},[comparison,quarter,previous]);
 const industryMoveRows=useMemo(()=>{const map=new Map<string,number>();for(const x of activity){const k=String(x.sector||'未分类');map.set(k,(map.get(k)||0)+Number(x.delta||0))}const all=[...map].map(([name,value])=>({name,value})).filter(x=>Math.abs(x.value)>=.02);const down=all.filter(x=>x.value<0).sort((a,b)=>a.value-b.value).slice(0,8);const up=all.filter(x=>x.value>0).sort((a,b)=>b.value-a.value).slice(0,8);return[...down,...up].sort((a,b)=>a.value-b.value)},[activity]);
 const persistence=useMemo(()=>{if(!data?.holdings?.length)return{top:[] as string[],matrix:[] as any[]};const top=selected.slice(0,10).map((x:any)=>String(x.stock_name));const matrix:any[]=[];top.forEach((name:string,yi:number)=>visiblePeriods.forEach((p:string,xi:number)=>{const r=data.holdings.find((x:any)=>x.quarter===p&&x.stock_name===name);matrix.push([xi,yi,r?.weight_pct||0])}));return{top,matrix}},[data,selected,visiblePeriods]);
 const localTrajectory=useMemo(()=>{if(!data?.holdings?.length||!visiblePeriods.length)return{periods:[] as string[],series:[] as any[],max_rank:10};const rankRows:any[]=[];for(const p of visiblePeriods){const rows=data.holdings.filter((x:any)=>x.quarter===p).slice().sort((a:any,b:any)=>Number(b.weight_pct)-Number(a.weight_pct));rows.forEach((x:any,i:number)=>rankRows.push({...x,rank:i+1}))}const selectedTop=selected.slice(0,5).map((x:any)=>String(x.stock_code));const stats=new Map<string,{name:string;appear:number;rankSum:number}>();for(const r of rankRows.filter(x=>x.rank<=10)){const k=String(r.stock_code),v=stats.get(k)||{name:String(r.stock_name),appear:0,rankSum:0};v.appear+=1;v.rankSum+=r.rank;stats.set(k,v)}const persistent=[...stats].sort((a,b)=>b[1].appear-a[1].appear||(a[1].rankSum/a[1].appear)-(b[1].rankSum/b[1].appear)).map(x=>x[0]);const candidates:string[]=[];for(const c of [...selectedTop,...persistent]){if(!candidates.includes(c))candidates.push(c);if(candidates.length>=8)break}const series=candidates.map(c=>{const rows=rankRows.filter(x=>String(x.stock_code)===c);const name=String(rows[rows.length-1]?.stock_name||c);const map=new Map(rows.map(x=>[x.quarter,x]));return{stock_code:c,stock_name:name,points:visiblePeriods.map(p=>{const r:any=map.get(p);return{period:p,rank:r?.rank??null,weight:r?.weight_pct??null}})}});const maxRank=Math.min(20,Math.max(10,...series.flatMap(s=>s.points.map((p:any)=>p.rank||0))));return{periods:visiblePeriods,series,max_rank:maxRank}},[data,selected,visiblePeriods]);
 const selectedHidden=useMemo(()=>{if(!data||!previous||!quarter)return{signals:[] as any[],coverage:0};const old=new Map(data.holdings.filter((x:any)=>x.quarter===previous).map((x:any)=>[String(x.stock_code),x]));const cur=new Map(data.holdings.filter((x:any)=>x.quarter===quarter).map((x:any)=>[String(x.stock_code),x]));const keys=[...new Set([...old.keys(),...cur.keys()])];let valid=0;const signals:any[]=[];for(const k of keys){const a:any=old.get(k),b:any=cur.get(k);const so=Number(a?.shares),sn=Number(b?.shares);if(!a||!b||!Number.isFinite(so)||!Number.isFinite(sn)||so<=0||sn<0)continue;valid++;const sc=(sn/so-1)*100,wd=Number(b?.weight_pct||0)-Number(a?.weight_pct||0);if(Math.abs(sc)<8)continue;const opposite=(sc>0&&wd<0)||(sc<0&&wd>0),masked=Math.abs(wd)<=.6||opposite;if(!masked)continue;signals.push({stock_code:k,stock_name:b?.stock_name||a?.stock_name,sector:b?.sector||a?.sector,share_change_pct:Number(sc.toFixed(2)),weight_delta:Number(wd.toFixed(2)),signal:sc>0?'隐形增仓':'隐形减仓',confidence:Math.abs(sc)>=15&&Math.abs(sc)<200?'高':'中'})}return{signals:signals.sort((a,b)=>Math.abs(b.share_change_pct)-Math.abs(a.share_change_pct)).slice(0,24),coverage:Number((valid/Math.max(1,keys.length)*100).toFixed(2))}},[data,previous,quarter]);
 const selectedSankey=useMemo(()=>migrationSankey(activity,Boolean(data?.metrics?.sector_mapped)),[activity,data?.metrics?.sector_mapped]);
 if(error)return <ErrorState message={error}/>;
 const holdingCols:ColumnDef<any>[]=[{accessorKey:'stock_name',header:'证券'},{accessorKey:'stock_code',header:'代码'},...(data?.metrics?.sector_mapped?[{accessorKey:'sector',header:'行业'} as ColumnDef<any>]:[]),{accessorKey:'weight_pct',header:'披露权重',cell:({getValue})=><span className="num">{Number(getValue()).toFixed(2)}%</span>}];
 const activityCols:ColumnDef<any>[]=[{accessorKey:'stock_name',header:'证券'},...(data?.metrics?.sector_mapped?[{accessorKey:'sector',header:'行业'} as ColumnDef<any>]:[]),{accessorKey:'weight_old',header:'前期',cell:({getValue})=><span className="num">{getValue()==null?'—':`${Number(getValue()).toFixed(2)}%`}</span>},{accessorKey:'weight_new',header:'本期',cell:({getValue})=><span className="num">{getValue()==null?'—':`${Number(getValue()).toFixed(2)}%`}</span>},{accessorKey:'delta',header:'变化',cell:({getValue})=>{const v=Number(getValue());return <span className={`num rebalance-delta ${v>=0?'positive':'negative'}`}>{v>=0?'+':''}{v.toFixed(2)} pp</span>}},{accessorKey:'activity',header:'状态',cell:({getValue})=>{const v=String(getValue());const tone=v.includes('上升')||v.includes('新进入')?'up':v.includes('下降')||v.includes('退出')?'down':'flat';return <span className={`activity-pill ${tone}`}>{v}</span>}}];
 const hiddenCols:ColumnDef<any>[]=[{accessorKey:'stock_name',header:'证券'},{accessorKey:'signal',header:'信号',cell:({getValue})=><span className={`signal-pill ${String(getValue()).includes('增')?'up':'down'}`}>{String(getValue())}</span>},{accessorKey:'share_change_pct',header:'持股数量变化',cell:({getValue})=>{const v=Number(getValue());return <span className={`num ${v>=0?'positive':'negative'}`}>{v>=0?'+':''}{v.toFixed(2)}%</span>}},{accessorKey:'weight_delta',header:'权重变化',cell:({getValue})=><span className="num">{Number(getValue())>=0?'+':''}{Number(getValue()).toFixed(2)} pp</span>},{accessorKey:'confidence',header:'可信度'}];
 const gapCols:ColumnDef<any>[]=[{accessorKey:'to_period',header:'报告期'},{accessorKey:'fund_return_pct',header:'基金收益',cell:({getValue})=><span className="num">{Number(getValue()).toFixed(2)}%</span>},{accessorKey:'disclosed_contribution_pct',header:'披露组合贡献',cell:({getValue})=><span className="num">{Number(getValue()).toFixed(2)}%</span>},{accessorKey:'return_gap_pct',header:'收益缺口',cell:({getValue})=>{const v=Number(getValue());return <span className={`num ${v>=0?'positive':'negative'}`}>{v>=0?'+':''}{v.toFixed(2)}%</span>}},{accessorKey:'holding_weight_coverage_pct',header:'披露覆盖',cell:({getValue})=><span className="num">{Number(getValue()).toFixed(2)}%</span>},{accessorKey:'confidence',header:'可信度'}];
 const peerCols:ColumnDef<any>[]=[{accessorKey:'fund_name',header:'相似基金',cell:({row,getValue})=><div className="explorer-name"><b>{String(getValue())}</b><small>{row.original.fund_code} · {row.original.fund_type}</small></div>},{accessorKey:'similarity_pct',header:'持仓相似度',cell:({getValue})=><span className="num strong">{Number(getValue()).toFixed(2)}%</span>},{accessorKey:'weighted_overlap_pct',header:'权重重合',cell:({getValue})=><span className="num">{Number(getValue()).toFixed(2)}%</span>},{accessorKey:'common_count',header:'共同证券',cell:({getValue})=><span className="num">{Number(getValue())}</span>},{accessorKey:'jaccard_pct',header:'证券集合重合',cell:({getValue})=><span className="num">{Number(getValue()).toFixed(2)}%</span>},{id:'common',header:'主要共同持仓',cell:({row})=><span className="peer-common">{(row.original.common_holdings||[]).join('、')||'—'}</span>}];
 const styleHist=advanced?.style_history||[];const selectedStyle=styleHist.find((x:any)=>x.period===quarter);const styleWindow=styleHist.filter((x:any)=>visiblePeriods.includes(x.period));
 const styleRadar=selectedStyle?[selectedStyle.size_score,selectedStyle.value_growth_score,selectedStyle.sector_concentration,selectedStyle.top10_concentration].map((v:any)=>v==null?0:Number(v)):[];
 return <><PageHeader title="基金研究" actions={<div className="fund-page-actions"><FundPicker value={code} onChange={setCode} label="选择基金"/>{mode==='local'&&code&&<TaskProgressButton task={historyTask} idleLabel="补齐历史" onClick={async()=>setHistoryTask(await api.startFundHistory(code,'standard'))}/>}</div>}/>
 <DataContext period={quarter} basis={comparison.label||data?.data_context?.comparison?.basis} sampleFunds={1} updatedAt={data?.data_context?.updated_at} note={comparison.label?`当前调仓比较使用 ${comparison.label} 口径。`:data?.data_context?.comparison?.note}/>
 {!data?<Loading label="正在加载"/>:<><div className="entity-head"><div><div className="entity-code">{data.fund.fund_code}</div><h2>{data.fund.fund_name}</h2><div className="entity-meta"><span>{data.fund.fund_type||'未分类'}</span>{data.fund.manager_name&&<span>{data.fund.manager_name}</span>}{data.fund.share_class_candidate&&<span>{data.fund.share_class_candidate} 份额</span>}</div></div><div className="entity-head-right"><div className="entity-tools"><SaveEntityButton entityType="fund" entityId={String(data.fund.fund_code)} entityName={String(data.fund.fund_name)} meta={{quarter}}/><MonitorRuleButton entityType="fund" entityId={String(data.fund.fund_code)} entityName={String(data.fund.fund_name)} current={{drift_score:peerLens?.fund?.drift_score,turnover_pct:peerLens?.fund?.turnover_pct,top10_concentration:peerLens?.fund?.top10_concentration,retention_pct:peerLens?.fund?.retention_pct}}/></div><div className="entity-tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>概览</button><button className={tab==='evolution'?'active':''} onClick={()=>setTab('evolution')}>调仓变化</button><button className={tab==='advanced'?'active':''} onClick={()=>setTab('advanced')}>深度分析</button><button className={tab==='positioning'?'active':''} onClick={()=>setTab('positioning')}>同类定位</button><button className={tab==='peers'?'active':''} onClick={()=>setTab('peers')}>持仓相似</button><button className={tab==='holdings'?'active':''} onClick={()=>setTab('holdings')}>持仓明细</button></div></div></div>
 {profile&&Object.keys(profile).length>0&&<div className="fund-profile-strip v8"><div><span>成立日期</span><b>{profile.inception_date||String(profile.inception_info||'—').split('/')[0]}</b></div><div><span>基金管理人</span><b>{profile.fund_company||'—'}</b></div><div><span>基金经理</span><b>{profile.manager_names||data.fund.manager_name||'—'}</b></div><div><span>资产规模</span><b>{profile.asset_scale||'—'}</b></div><div className="benchmark"><span>业绩比较基准</span><b title={profile.benchmark||''}>{profile.benchmark||'—'}</b></div></div>}
 <MetricStrip items={[{label:'可用报告期',value:periods.length,sub:'季度披露'},{label:'当前报告期',value:quarter||'—',sub:previous?`对比 ${previous}`:''},{label:'披露证券数',value:selected.length,sub:'当前报告期'},{label:'前十大权重',value:selected.length?`${selected.slice(0,10).reduce((s:number,x:any)=>s+(Number(x.weight_pct)||0),0).toFixed(2)}%`:'—',sub:'当前报告期'}]}/>
 {periods.length>0?<QuarterRail periods={periods} value={quarter} onChange={setQuarter} playable={tab!=='positioning'&&tab!=='peers'}/>:<EmptyState title="暂无季度持仓" body="当前基金没有可用持仓记录。"/>}
 {periods.length>0&&tab==='overview'&&<>
 <div className="grid two-wide"><Panel title="核心持仓" meta={<span>{quarter} 前 8 大披露持仓</span>}><Chart height={420} option={{tooltip:{trigger:'axis',backgroundColor:'#fff',borderColor:'#e4e7ec',textStyle:{color:'#344054'},formatter:(ps:any[])=>{const head=ps?.[0]?.axisValue||'';return[head,...(ps||[]).filter((x:any)=>x.data!=null).map((x:any)=>`${x.marker}${x.seriesName}：${Number(x.data).toFixed(2)}%`)].join('<br/>')}},legend:{top:0,type:'scroll',textStyle:{color:'#667085'}},grid:{left:50,right:20,top:58,bottom:30},xAxis:{type:'category',data:visiblePeriods,axisLabel:{color:'#98a2b3'},axisLine:{lineStyle:{color:'#e4e7ec'}}},yAxis:{type:'value',axisLabel:{formatter:'{value}%',color:'#98a2b3'},splitLine:{lineStyle:{color:'#eef0f3'}}},series:selected.slice(0,8).map((item:any,i:number)=>({name:item.stock_name,type:'line',showSymbol:true,symbolSize:(_v:any,p:any)=>p?.name===quarter?7:0,smooth:.18,connectNulls:false,lineStyle:{width:i<3?2.2:1.5},data:visiblePeriods.map((p:string)=>data.holdings.find((x:any)=>x.quarter===p&&String(x.stock_code)===String(item.stock_code))?.weight_pct??null),markLine:i===0?{silent:true,symbol:'none',label:{show:true,formatter:quarter,color:'#667085'},lineStyle:{color:'#b8c2cf',type:'dashed'},data:[{xAxis:quarter}]}:undefined}))}}/></Panel><Panel title="当前持仓"><DataTable data={selected.slice(0,15)} columns={holdingCols} maxHeight={420}/></Panel></div>
 <Panel title="持仓排名轨迹" meta={<span>{quarter} 周边 {localTrajectory.periods.length} 个报告期</span>}>{localTrajectory.series?.length?<Chart height={420} option={{tooltip:{trigger:'axis',confine:true,formatter:(ps:any[])=>{const head=ps?.[0]?.axisValue||'';return [head,...(ps||[]).filter((x:any)=>x.data!=null).map((x:any)=>`${x.marker}${x.seriesName}：第 ${x.data} 名`)].join('<br/>')}},legend:{top:0,type:'scroll',textStyle:{color:'#667085'}},grid:{left:44,right:28,top:58,bottom:30,containLabel:true},xAxis:{type:'category',data:localTrajectory.periods,axisLabel:{color:'#98a2b3'}},yAxis:{type:'value',inverse:true,min:1,max:localTrajectory.max_rank||15,minInterval:1,axisLabel:{formatter:(v:number)=>`#${v}`,color:'#98a2b3'},splitLine:{lineStyle:{color:'#eef0f3'}}},series:localTrajectory.series.map((s:any,i:number)=>({name:s.stock_name,type:'line',showSymbol:true,symbolSize:(_v:any,p:any)=>p?.name===quarter?8:5,connectNulls:false,smooth:.12,data:s.points.map((p:any)=>p.rank),lineStyle:{width:2},markLine:i===0?{silent:true,symbol:'none',label:{show:false},lineStyle:{color:'#b8c2cf',type:'dashed'},data:[{xAxis:quarter}]}:undefined,emphasis:{focus:'series'}}))}}/>:<EmptyState title="历史深度不足" body="至少需要多个报告期生成持仓排名轨迹。"/>}</Panel>
 </>}
 {periods.length>0&&tab==='evolution'&&<>{!previous?<EmptyState title="缺少前期数据" body="当前报告期没有可比较记录。"/>:<>
 <Panel title="调仓总览" className="rebalance-panel"><RebalanceBoard activity={activity}/></Panel>
 <div className="grid two-equal">
  {data.metrics?.sector_mapped?<Panel title="行业迁移" meta={<span>增配 / 减配各最多 8 个行业</span>}><Chart height={410} option={{tooltip:{trigger:'axis',axisPointer:{type:'shadow'},confine:true,formatter:(items:any[])=>{const p=items?.[0];return p?`${p.name}<br/>变化：${Number(p.value)>=0?'+':''}${Number(p.value).toFixed(2)} pp`:''}},grid:{left:22,right:24,top:18,bottom:26,containLabel:true},xAxis:{type:'value',splitLine:{lineStyle:{color:'#eef0f3'}},axisLabel:{color:'#98a2b3',formatter:(v:number)=>Number(v).toFixed(2)}},yAxis:{type:'category',data:industryMoveRows.map(x=>x.name),axisLabel:{color:'#475467',width:155,overflow:'truncate'},axisLine:{show:false},axisTick:{show:false}},series:[{type:'bar',barWidth:10,data:industryMoveRows.map(x=>({value:Number(x.value.toFixed(2)),itemStyle:{color:x.value>=0?'#315c94':'#c95b66',borderRadius:x.value>=0?[0,4,4,0]:[4,0,0,4]}}))}]}}/></Panel>:<Panel title="持仓持续性"><Chart height={410} option={{tooltip:{position:'top',formatter:(p:any)=>`${persistence.top[p.value[1]]}<br/>${visiblePeriods[p.value[0]]}<br/>权重：${Number(p.value[2]).toFixed(2)}%`},grid:{left:108,right:18,top:16,bottom:48},xAxis:{type:'category',data:visiblePeriods,axisLabel:{color:'#98a2b3'}},yAxis:{type:'category',data:persistence.top,axisLabel:{color:'#475467'},axisLine:{show:false},axisTick:{show:false}},visualMap:{min:0,max:Math.max(10,...persistence.matrix.map(x=>x[2])),orient:'horizontal',left:'center',bottom:0,textStyle:{color:'#98a2b3'},inRange:{color:['#f3f6fa','#d8e4f2','#8eadd2','#315c94']}},series:[{type:'heatmap',data:persistence.matrix,itemStyle:{borderWidth:2,borderColor:'#fff'}}]}}/></Panel>}
  <Panel title="重大买卖披露" meta={mode==='local'&&!majorChanges.length?<TaskProgressButton task={majorTask} idleLabel="同步重大变动" onClick={async()=>setMajorTask(await api.startMajorChanges(code,majorYears.length?majorYears:[Number(String(quarter).slice(0,4))]))}/>:undefined}>{majorChanges.length?<MajorChangeBoard rows={majorChanges}/>:<EmptyState title="暂无重大变动记录" body=""/>}</Panel>
 </div>
 <Panel title="调仓明细"><DataTable data={activity} columns={activityCols} maxHeight={500}/></Panel>
 </>}</>}
 {periods.length>0&&tab==='advanced'&&<>{advancedError?<ErrorState compact message={advancedError} onRetry={()=>{setAdvancedError('');setAdvanced(null)}}/>:!advanced?<Loading compact label="正在计算深度分析"/>:<>
 <div className="advanced-kpis"><div><span>风格漂移</span><b>{fmt(selectedStyle?.drift_score,2)}</b><small>{quarter} · {selectedStyle?.drift_level||'—'}</small></div><div><span>规模风格</span><b>{fmt(selectedStyle?.size_score,2)}</b><small>{quarter} · 小盘至大盘</small></div><div><span>价值成长</span><b>{fmt(selectedStyle?.value_growth_score,2)}</b><small>{quarter} · 价值至成长</small></div><div><span>行业集中</span><b>{fmt(selectedStyle?.sector_concentration,2)}</b><small>{quarter} · 行业配置集中度</small></div></div>
 <div className="grid two-equal"><Panel title="多维风格画像" meta={<span>{quarter}</span>}>{styleRadar.length?<Chart height={390} option={{tooltip:{},radar:{indicator:[{name:'规模',max:100},{name:'价值成长',max:100},{name:'行业集中',max:100},{name:'持仓集中',max:100}],splitNumber:4,axisName:{color:'#667085'},splitLine:{lineStyle:{color:'#e7e9ee'}},splitArea:{areaStyle:{color:['#fbfcfd','#f7f9fb']}}},series:[{type:'radar',data:[{value:styleRadar,name:quarter,areaStyle:{color:'rgba(49,92,148,.14)'},lineStyle:{color:'#315c94',width:2},itemStyle:{color:'#315c94'}}]}]}}/>:<EmptyState title="证券主表覆盖不足" body="请在数据中心补齐证券主表。"/>}</Panel><Panel title="风格轨迹" meta={<span>当前 {quarter}</span>}><Chart height={390} option={{tooltip:{trigger:'axis'},legend:{top:0,textStyle:{color:'#667085'}},grid:{left:48,right:18,top:48,bottom:32},xAxis:{type:'category',data:styleWindow.map((x:any)=>x.period),axisLabel:{color:'#98a2b3'}},yAxis:{type:'value',min:0,max:100,splitLine:{lineStyle:{color:'#eef0f3'}},axisLabel:{color:'#98a2b3'}},series:[{name:'规模',type:'line',smooth:.25,showSymbol:true,symbolSize:(_v:any,p:any)=>p?.name===quarter?7:0,data:styleWindow.map((x:any)=>x.size_score),markLine:{silent:true,symbol:'none',label:{show:false},lineStyle:{color:'#b8c2cf',type:'dashed'},data:[{xAxis:quarter}]}},{name:'价值成长',type:'line',smooth:.25,showSymbol:true,symbolSize:(_v:any,p:any)=>p?.name===quarter?7:0,data:styleWindow.map((x:any)=>x.value_growth_score)},{name:'行业集中',type:'line',smooth:.25,showSymbol:true,symbolSize:(_v:any,p:any)=>p?.name===quarter?7:0,data:styleWindow.map((x:any)=>x.sector_concentration)},{name:'持仓集中',type:'line',smooth:.25,showSymbol:true,symbolSize:(_v:any,p:any)=>p?.name===quarter?7:0,data:styleWindow.map((x:any)=>x.top10_concentration)},{name:'漂移',type:'line',smooth:.25,showSymbol:true,symbolSize:(_v:any,p:any)=>p?.name===quarter?8:0,lineStyle:{width:2.5},data:styleWindow.map((x:any)=>x.drift_score)}]}}/></Panel></div>
 <Panel title="配置迁移估计" meta={<span>{previous?`${previous} → ${quarter}`:quarter}</span>} className="sankey-panel">{selectedSankey.links.length?<SankeyChart nodes={selectedSankey.nodes} links={selectedSankey.links}/>:<EmptyState title="暂无迁移图" body="当前报告期没有形成可展示的双向配置变化。"/>}</Panel>
 <div className="grid two-equal"><Panel title="收益缺口">{advanced.return_gap?.length?<Chart height={410} option={{tooltip:{trigger:'axis',formatter:(ps:any[])=>{const p=ps?.[0];return p?`${p.axisValue}<br/>收益缺口：${Number(p.value)>=0?'+':''}${Number(p.value).toFixed(2)}%`:''}},grid:{left:52,right:18,top:20,bottom:34,containLabel:true},xAxis:{type:'category',data:advanced.return_gap.map((x:any)=>x.to_period),axisLabel:{color:'#98a2b3'}},yAxis:{type:'value',axisLabel:{formatter:'{value}%',color:'#98a2b3'},splitLine:{lineStyle:{color:'#eef0f3'}}},series:[{type:'bar',barWidth:16,data:advanced.return_gap.map((x:any)=>({value:x.return_gap_pct,itemStyle:{color:x.to_period===quarter?(x.return_gap_pct>=0?'#2f8f70':'#c95b66'):'#c7ced8',opacity:x.to_period===quarter?1:.52,borderRadius:[4,4,0,0]}}))}]}}/>:<div className="analysis-empty-action"><EmptyState compact title="暂无收益缺口数据" body={mode==='local'?'当前基金缺少计算所需的净值或价格数据。':'演示数据不加载外部行情。'}/>{mode==='local'&&<TaskProgressButton task={gapTask} idleLabel="补齐分析数据" onClick={async()=>setGapTask(await api.startReturnGap(code,3,'standard'))}/>}</div>}</Panel><Panel title="隐形调仓信号" meta={<span>{previous?`${previous} → ${quarter}`:quarter}</span>}>{selectedHidden.coverage<20?<EmptyState title="持股数量覆盖不足" body="当前数据不足以稳定识别隐形调仓。"/>:selectedHidden.signals.length?<DataTable data={selectedHidden.signals} columns={hiddenCols} maxHeight={420}/>:<EmptyState title="未发现明显信号" body="当前两个报告期没有满足阈值的隐形调仓信号。"/>}</Panel></div>
 <Panel title="收益缺口明细">{advanced.return_gap?.length?<DataTable data={advanced.return_gap} columns={gapCols} maxHeight={420}/>:<EmptyState title="暂无明细" body="当前没有可用的收益缺口记录。"/>}</Panel>
 </>}</>}
 {periods.length>0&&tab==='positioning'&&<>
 {peerLensError?<ErrorState compact message={peerLensError} onRetry={async()=>{setPeerLensError('');setPeerLens(null);try{setPeerLens(await api.fundPeerLens(mode,code,quarter,peerUniverse))}catch(e:any){setPeerLensError(e?.message||String(e))}}}/>:!peerLens?<Loading compact label="正在计算同类定位"/>:<>
  <div className="peer-lens-toolbar"><div className="segmented">{(peerLens.universes||[]).map((u:any)=><button key={u.key} className={peerUniverse===u.key?'active':''} onClick={()=>setPeerUniverse(u.key)}>{u.label}</button>)}</div><span>{peerLens.peer_count||0} 只可比基金 · {peerLens.period}</span></div>
  {peerLens.metrics?.length?<><div className="peer-lens-grid">{peerLens.metrics.map((m:any)=><div className="peer-metric-card" key={m.key}><div className="peer-metric-head"><span title={m.help}>{m.label}</span><div className="peer-metric-value"><b>{fmt(m.value,2)}{m.unit}</b><em>P{Math.round(Number(m.percentile||0))}</em></div></div><div className="percentile-track"><i style={{left:`${Math.max(1,Math.min(99,m.percentile))}%`}}/></div><div className="quartile-row"><span>P25 {fmt(m.p25,2)}{m.unit}</span><span>P50 {fmt(m.median,2)}{m.unit}</span><span>P75 {fmt(m.p75,2)}{m.unit}</span></div></div>)}</div><Panel title="相近行为基金" meta={<span>标准化距离越低，行为与风格越接近</span>}>{peerLens.peers?.length?<DataTable data={peerLens.peers} columns={[{accessorKey:'fund_name',header:'基金',cell:({row,getValue}:any)=><div className="explorer-name"><b>{String(getValue())}</b><small>{row.original.fund_code}</small></div>},{accessorKey:'distance',header:'标准化距离',cell:({getValue}:any)=><span className="num">{Number(getValue()).toFixed(2)}</span>},{accessorKey:'turnover_pct',header:'调仓强度',cell:({getValue}:any)=><span className="num">{fmt(getValue(),2)}%</span>},{accessorKey:'top10_concentration',header:'前十集中',cell:({getValue}:any)=><span className="num">{fmt(getValue(),2)}%</span>},{accessorKey:'drift_score',header:'风格漂移',cell:({getValue}:any)=><span className="num">{fmt(getValue(),2)}</span>}]} maxHeight={420} onRowClick={(r:any)=>navigate(`/funds?code=${encodeURIComponent(r.fund_code)}`)}/>:<EmptyState title="没有足够的可比基金" body="当前比较范围样本不足。"/>}</Panel></>:<EmptyState title="同类数据不足" body="当前基金缺少横截面可比指标。"/>}
 </>}</>}
 {periods.length>0&&tab==='peers'&&<>
 {peersError?<ErrorState compact message={peersError} onRetry={()=>{setPeersError('');setPeers(null);api.fundPeers(mode,code,quarter,15).then(x=>{setPeers(x);setSelectedPeerCode(String(x?.peers?.[0]?.fund_code||''))}).catch((e:any)=>setPeersError(e?.message||String(e)))}}/>:!peers?<Loading compact label="正在计算持仓相似度"/>:peers.peers?.length?<>
 <MetricStrip items={[{label:'最相似基金',value:peers.peers[0]?.fund_name||'—',sub:`持仓相似度 ${Number(peers.peers[0]?.similarity_pct||0).toFixed(2)}%`},{label:'最高权重重合',value:`${Number(Math.max(...peers.peers.map((x:any)=>Number(x.weighted_overlap_pct||0)))).toFixed(2)}%`,sub:'共同证券的较小权重之和'},{label:'可比较基金',value:peers.peers.length,sub:quarter},{label:'当前前十集中',value:selected.length?`${selected.slice(0,10).reduce((s:number,x:any)=>s+Number(x.weight_pct||0),0).toFixed(2)}%`:'—',sub:quarter}]}/>
 <div className="grid two-equal peer-map-grid"><Panel title="相似基金地图" meta={<span>{quarter} · 点击圆点查看拆解</span>}><Chart height={420} option={{tooltip:{confine:true,formatter:(p:any)=>`${p.data.name}<br/>持仓相似度：${Number(p.data.sim).toFixed(2)}%<br/>权重重合：${Number(p.data.overlap).toFixed(2)}%<br/>共同证券：${p.data.common}`},grid:{left:30,right:24,top:30,bottom:56,containLabel:true},xAxis:{type:'value',min:0,max:100,name:'持仓相似度 %',nameLocation:'middle',nameGap:34,nameTextStyle:{color:'#98a2b3',fontSize:11},splitLine:{lineStyle:{color:'#eef0f3'}},axisLabel:{color:'#98a2b3'}},yAxis:{type:'value',min:0,max:100,name:'权重重合 %',nameLocation:'middle',nameGap:50,nameTextStyle:{color:'#98a2b3',fontSize:11},splitLine:{lineStyle:{color:'#eef0f3'}},axisLabel:{color:'#98a2b3'}},series:[{type:'scatter',data:peers.peers.map((x:any)=>({name:x.fund_name,code:x.fund_code,value:[x.similarity_pct,x.weighted_overlap_pct],sim:x.similarity_pct,overlap:x.weighted_overlap_pct,common:x.common_count,symbolSize:Math.max(10,Math.min(28,8+x.common_count*1.2)),itemStyle:{color:String(x.fund_code)===String(selectedPeer?.fund_code)?'#173f6d':'#6f8fb8',opacity:String(x.fund_code)===String(selectedPeer?.fund_code) ? .95 : .62}}))}]}} onEvents={{click:(p:any)=>p?.data?.code&&setSelectedPeerCode(String(p.data.code))}}/></Panel><Panel title="相似度拆解" meta={selectedPeer?<span>{selectedPeer.fund_name}</span>:undefined}>{selectedPeer?<div className="similarity-breakdown"><div className="similarity-peer-head"><div><small>{selectedPeer.fund_code}</small><b>{selectedPeer.fund_name}</b></div><button type="button" onClick={()=>{const next=String(selectedPeer.fund_code);setTab('overview');setSelectedPeerCode('');setParams({code:next});setCode(next);window.scrollTo({top:0,behavior:'smooth'});navigate(`/funds?code=${encodeURIComponent(next)}`,{replace:false})}}>查看基金</button></div>{[{label:'持仓相似度',value:Number(selectedPeer.similarity_pct||0),help:'披露权重向量余弦相似度'},{label:'权重重合',value:Number(selectedPeer.weighted_overlap_pct||0),help:'共同证券上的较小权重之和'},{label:'证券集合重合',value:Number(selectedPeer.jaccard_pct||0),help:'共同证券数 / 两基金证券并集'}].map(x=><div className="similarity-row" key={x.label}><div><span>{x.label}</span><b>{x.value.toFixed(2)}%</b></div><div className="similarity-bar"><i style={{width:`${Math.max(0,Math.min(100,x.value))}%`}}/></div><small>{x.help}</small></div>)}<div className="similarity-common"><span>共同证券 {selectedPeer.common_count}</span><p>{(selectedPeer.common_holdings||[]).join('、')||'暂无可展示的共同重仓'}</p></div><p className="similarity-method">三项指标分别展示，不合成为黑箱评分。</p></div>:<EmptyState compact title="请选择相似基金" body="点击左侧散点或下方基金查看指标拆解。"/>}</Panel></div>
 <Panel title="最相似基金"><DataTable data={peers.peers} columns={peerCols} maxHeight={560} onRowClick={(r:any)=>setSelectedPeerCode(String(r.fund_code))}/></Panel>
 </>:<EmptyState title="没有足够的可比基金" body="当前报告期没有找到可用于相似度计算的其他主动偏股基金。"/>}
 </>}
 {periods.length>0&&tab==='holdings'&&<Panel title="持仓明细"><DataTable data={selected} columns={holdingCols} maxHeight={620}/></Panel>}
 </>}</>;
}
