import { useEffect,useMemo,useState } from "react";
import { useSearchParams } from "react-router-dom";
import type { ColumnDef } from "@tanstack/react-table";
import { api } from "../lib/api";
import { useAppStore } from "../store/useAppStore";
import { PageHeader } from "../components/PageHeader";
import { MetricStrip } from "../components/MetricStrip";
import { Panel } from "../components/Panel";
import { Chart } from "../components/Chart";
import { DataTable } from "../components/DataTable";
import { DataContext } from "../components/DataContext";
import { Loading,ErrorState,EmptyState } from "../components/Loading";
import { ManagerPicker } from "../components/RemotePicker";
import { sortPeriods,categoryGrid } from "../lib/chartUtils";
import { SaveEntityButton } from "../components/SaveEntityButton";

export function ManagersPage(){
 const mode=useAppStore(s=>s.mode);const[params,setParams]=useSearchParams();const[mid,setMid]=useState(params.get('mid')||'');const[data,setData]=useState<any>(null);const[style,setStyle]=useState<any>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(false);const[styleLoading,setStyleLoading]=useState(false);
 useEffect(()=>{const wanted=params.get('mid');if(wanted){setMid(wanted);return}api.managerCatalog(mode).then(x=>{if(x[0])setMid(x[0].manager_id)}).catch((e:any)=>setError(e?.message||"请求未完成，请稍后重试"))},[mode]);
 useEffect(()=>{if(!mid)return;setError('');setLoading(true);api.managerById(mode,mid).then(x=>{setData(x);setStyle(null);setParams({mid});api.touchRecent({entity_type:'manager',entity_id:String(x.manager.manager_id||mid),entity_name:String(x.manager.manager_name||mid),route:`/managers?mid=${encodeURIComponent(String(x.manager.manager_id||mid))}`}).catch(()=>{});setStyleLoading(true);api.managerStyle(mode,x.manager.manager_name,x.manager.company||'').then(setStyle).catch(()=>setStyle(null)).finally(()=>setStyleLoading(false))}).catch(e=>setError(e?.message||String(e))).finally(()=>setLoading(false))},[mid,mode]);
 const heat=useMemo(()=>{const h=data?.sector_history||[];const periods=sortPeriods(h.map((x:any)=>String(x.quarter||'')));const totals=new Map<string,number>();periods.forEach(p=>totals.set(p,h.filter((x:any)=>x.quarter===p).reduce((s:number,x:any)=>s+(x.weight_pct||0),0)));const agg=new Map<string,number>();h.forEach((x:any)=>agg.set(x.sector,(agg.get(x.sector)||0)+(x.weight_pct||0)));const sectors=[...agg].sort((a,b)=>b[1]-a[1]).slice(0,10).map(x=>x[0]);const matrix:any[]=[];sectors.forEach((s,yi)=>periods.forEach((p,xi)=>{const row=h.find((x:any)=>x.quarter===p&&x.sector===s);const total=totals.get(p)||1;matrix.push([xi,yi,row?(row.weight_pct/total*100):0])}));return{periods,sectors,matrix}},[data]);
 if(error)return <ErrorState message={error}/>;
 const cols:ColumnDef<any>[]=[{accessorKey:'stock_name',header:'证券'},...(data?.metrics?.sector_mapped?[{accessorKey:'sector',header:'行业'} as ColumnDef<any>]:[]),{accessorKey:'fund_coverage',header:'覆盖产品数',cell:({getValue})=><span className="num">{Number(getValue()).toFixed(0)}</span>},{accessorKey:'avg_weight',header:'平均权重',cell:({getValue})=><span className="num">{Number(getValue()).toFixed(2)}%</span>},{accessorKey:'sum_weight',header:'权重合计',cell:({getValue})=><span className="num">{Number(getValue()).toFixed(2)}%</span>}];
 const timeline=style?.timeline||[];const last=timeline[timeline.length-1];
 return <><PageHeader eyebrow="基金经理研究" title="基金经理" actions={<ManagerPicker value={mid} onChange={(item)=>setMid(item.manager_id)}/>}/>
 {loading&&data?<div className="research-refresh-indicator"><span></span>正在切换基金经理，当前结果可继续查看</div>:null}
 {!data?<Loading label="正在加载基金经理研究"/>:<><div className="manager-hero"><div className="avatar-large">{String(data.manager.manager_name||'?').slice(0,2)}</div><div><span>{data.manager.company||'基金管理人'}</span><h2>{data.manager.manager_name}</h2><p>{data.metrics?.latest_period?`最近持仓报告期 ${data.metrics.latest_period}`:'暂无可用持仓报告期'}</p></div><div className="manager-hero-actions"><SaveEntityButton entityType="manager" entityId={String(data.manager.manager_id||mid)} entityName={String(data.manager.manager_name)} meta={{company:data.manager.company}}/></div></div>
 <DataContext period={data.metrics?.latest_period} basis="Top 10 Comparable" note="经理风格时间轴按可比披露口径聚合管理产品。"/>
 <MetricStrip items={[{label:'从业年限',value:data.manager.career_years!=null?`${Number(data.manager.career_years).toFixed(2)} 年`:'—',sub:'投资管理经验'},{label:'当前管理规模',value:data.manager.aum_yi!=null?`${Number(data.manager.aum_yi).toFixed(2)} 亿`:'—',sub:'当前管理资产'},{label:'已采集产品',value:data.metrics?.collected_funds??0,sub:`映射 ${data.fund_codes.length} 个基金代码`},{label:'当前漂移',value:last?.drift_score??'—',sub:last?`${last.fund_count} 个产品聚合`:'暂无风格数据'}]}/>
 <div className="grid two-wide"><Panel title="经理风格时间轴" meta={<span>{styleLoading?'正在更新风格…':style?.attribution_basis==='historical_tenure'?'历史任职口径':'当前产品集合口径'}</span>}>{timeline.length?<Chart height={440} option={{tooltip:{trigger:'axis'},legend:{top:0,textStyle:{color:'#667085'}},grid:{left:50,right:18,top:52,bottom:30},xAxis:{type:'category',data:timeline.map((x:any)=>x.period),axisLabel:{color:'#98a2b3'}},yAxis:{type:'value',min:0,max:100,axisLabel:{color:'#98a2b3'},splitLine:{lineStyle:{color:'#eef0f3'}}},series:[{name:'规模',type:'line',smooth:.25,showSymbol:false,data:timeline.map((x:any)=>x.size_score)},{name:'价值成长',type:'line',smooth:.25,showSymbol:false,data:timeline.map((x:any)=>x.value_growth_score)},{name:'行业集中',type:'line',smooth:.25,showSymbol:false,data:timeline.map((x:any)=>x.sector_concentration)},{name:'持仓集中',type:'line',smooth:.25,showSymbol:false,data:timeline.map((x:any)=>x.top10_concentration)},{name:'漂移',type:'line',smooth:.25,showSymbol:false,lineStyle:{width:2.8},data:timeline.map((x:any)=>x.drift_score)}]}}/>:<EmptyState title="暂无风格时间轴" body="先补齐相关基金持仓与证券主表。"/>}</Panel><Panel title="当前风格画像">{last?<Chart height={440} option={{radar:{indicator:[{name:'规模',max:100},{name:'价值成长',max:100},{name:'行业集中',max:100},{name:'持仓集中',max:100}],splitNumber:4,axisName:{color:'#667085'},splitLine:{lineStyle:{color:'#e7e9ee'}},splitArea:{areaStyle:{color:['#fbfcfd','#f7f9fb']}}},series:[{type:'radar',data:[{value:[last.size_score||0,last.value_growth_score||0,last.sector_concentration||0,last.top10_concentration||0],areaStyle:{color:'rgba(49,92,148,.14)'},lineStyle:{color:'#315c94',width:2},itemStyle:{color:'#315c94'}}]}]}}/>:<EmptyState title="暂无风格画像" body="证券主表覆盖不足。"/>}</Panel></div>
 <div className="grid two-equal">{data.metrics?.sector_mapped?<Panel title="行业配置变化">{heat.matrix.length?<Chart height={410} option={{tooltip:{position:'top'},grid:{left:106,right:18,top:14,bottom:52},xAxis:{type:'category',data:heat.periods,axisLabel:{color:'#98a2b3'}},yAxis:{type:'category',data:heat.sectors,axisLabel:{color:'#475467'},axisLine:{show:false},axisTick:{show:false}},visualMap:{min:0,max:Math.max(10,...heat.matrix.map(x=>x[2])),orient:'horizontal',left:'center',bottom:0,textStyle:{color:'#98a2b3'},inRange:{color:['#f4f7fb','#dbe5f4','#91add6','#315c94']}},series:[{type:'heatmap',data:heat.matrix,itemStyle:{borderWidth:2,borderColor:'#fff'}}]}}/>:<EmptyState title="暂无行业历史" body="证券行业映射尚未覆盖。"/>}</Panel>:<Panel title="高确信持仓">{data.consensus?.length?<Chart height={410} option={{tooltip:{trigger:'axis'},grid:categoryGrid(18,18,16,24),xAxis:{type:'value',axisLabel:{formatter:'{value}%',color:'#98a2b3'},splitLine:{lineStyle:{color:'#eef0f3'}}},yAxis:{type:'category',data:data.consensus.slice(0,12).map((x:any)=>x.stock_name).reverse(),axisLabel:{color:'#475467'},axisLine:{show:false},axisTick:{show:false}},series:[{type:'bar',barWidth:10,data:data.consensus.slice(0,12).map((x:any)=>x.sum_weight).reverse(),itemStyle:{color:'#315c94'}}]}}/>:<EmptyState title="暂无持仓数据" body="请先采集当前管理产品的季度持仓。"/>}</Panel>}<Panel title="跨产品共同持仓"><DataTable data={data.consensus||[]} columns={cols} maxHeight={410}/></Panel></div>
 </>}</>;
}
