import { useCallback, useEffect, useState } from "react";
import type { ColumnDef } from "@tanstack/react-table";
import { RefreshCw } from "lucide-react";
import { api } from "../lib/api";
import { useAppStore } from "../store/useAppStore";
import { PageHeader } from "../components/PageHeader";
import { MetricStrip } from "../components/MetricStrip";
import { Panel } from "../components/Panel";
import { Chart } from "../components/Chart";
import { DataTable } from "../components/DataTable";
import { DataContext } from "../components/DataContext";
import { Loading, ErrorState, EmptyState } from "../components/Loading";
import { categoryGrid, sortPeriods } from "../lib/chartUtils";

export function PulsePage(){
  const mode=useAppStore(s=>s.mode);const[data,setData]=useState<any>(null);const[error,setError]=useState("");const[stale,setStale]=useState(false);const[refreshing,setRefreshing]=useState(false);
  const cacheKey=`fundscope:pulse:${mode}`;
  const load=useCallback(async(showLoader=true)=>{if(showLoader&&!data)setData(null);setError('');setRefreshing(true);try{const x=await api.overview(mode);setData(x);setStale(false);try{sessionStorage.setItem(cacheKey,JSON.stringify({at:Date.now(),data:x}))}catch{}}catch(e:any){let cached:any=null;try{const raw=sessionStorage.getItem(cacheKey);if(raw)cached=JSON.parse(raw)?.data}catch{}if(cached){setData(cached);setStale(true);setError(e?.message||String(e))}else setError(e?.message||String(e))}finally{setRefreshing(false)}},[mode,cacheKey,data]);
  useEffect(()=>{let cached:any=null;try{const raw=sessionStorage.getItem(cacheKey);if(raw)cached=JSON.parse(raw)?.data}catch{}if(cached){setData(cached);setStale(true);load(false)}else load(true)},[mode]);
  if(error&&!data)return <ErrorState message={error} onRetry={()=>load(true)}/>;if(!data)return <Loading label="正在生成市场脉搏"/>;
  const asset=data.asset_history||[];const quarters=sortPeriods(asset.map((x:any)=>String(x.quarter||"")));const sectorHistory=data.sector_history||[];const sectorPeriods=sortPeriods(sectorHistory.map((x:any)=>String(x.quarter||"")));const sectorLatest=sectorPeriods.length?sectorHistory.filter((x:any)=>x.quarter===sectorPeriods[sectorPeriods.length-1]).sort((a:any,b:any)=>b.weight_pct-a.weight_pct).slice(0,10):[];const changes=data.coverage_change||[];const movers=[...changes.slice(0,7),...changes.slice(-7)].sort((a:any,b:any)=>a.delta-b.delta);
  const cols:ColumnDef<any>[]=[{accessorKey:"stock_name",header:"证券"},{accessorKey:"sector",header:"行业"},{accessorKey:"fund_count",header:"覆盖基金数",cell:({getValue})=><span className="num">{Number(getValue()).toLocaleString()}</span>},{accessorKey:"market_value_yi",header:"持仓市值",cell:({getValue})=><span className="num">{getValue()!=null?`${Number(getValue()).toFixed(2)} 亿`:"—"}</span>}];
  return <><PageHeader eyebrow="市场研究" title="市场脉搏" actions={<button className="soft-action" onClick={()=>load(false)} disabled={refreshing}><RefreshCw size={14} className={refreshing?'spin':''}/>{refreshing?'刷新中':'刷新'}</button>}/><DataContext period={data.latest_period} basis="Market aggregate"/>{stale&&<div className="stale-banner"><span>当前展示最近一次成功结果，后台刷新暂未完成。</span><button onClick={()=>load(false)}>重新加载</button></div>}
  <MetricStrip items={[{label:"偏股研究池",value:Number(data.fund_count||0).toLocaleString(),sub:mode==="demo"?"演示样本":"基金主体"},{label:"基金经理",value:Number(data.manager_count||0).toLocaleString(),sub:"当前经理记录"},{label:"持仓记录",value:Number(data.holding_rows||0).toLocaleString(),sub:"季度披露持仓"},{label:"最新报告期",value:data.latest_period||"—",sub:"当前可用披露期"}]}/>
  <div className="grid two-wide"><Panel title="大类资产配置" meta={<span>{quarters.length?`${quarters[0]} 至 ${quarters[quarters.length-1]} · 共 ${quarters.length} 季`:"暂无数据"}</span>}>{quarters.length?<Chart height={360} option={{tooltip:{trigger:"axis",confine:true},legend:{top:0,textStyle:{color:"#667085"}},grid:{left:22,right:22,top:46,bottom:quarters.length>20?58:32,containLabel:true},xAxis:{type:"category",data:quarters,boundaryGap:false,axisLabel:{color:"#98a2b3",hideOverlap:true,interval:quarters.length>28?Math.ceil(quarters.length/14)-1:0},axisLine:{lineStyle:{color:"#e4e7ec"}}},yAxis:{type:"value",min:0,max:100,name:"配置权重 %",nameLocation:"middle",nameGap:48,nameTextStyle:{color:"#98a2b3",fontSize:11},axisLabel:{formatter:"{value}%",color:"#98a2b3"},splitLine:{lineStyle:{color:"#eef0f3"}}},dataZoom:quarters.length>20?[{type:"inside",start:0,end:100,filterMode:"none"},{type:"slider",height:16,bottom:5,start:0,end:100,filterMode:"none",borderColor:"#e4e7ec",backgroundColor:"#f8fafc",fillerColor:"rgba(49,92,148,.10)",handleStyle:{color:"#7f9abb"},textStyle:{color:"#98a2b3",fontSize:9}}]:[],series:[{name:"股票权益",type:"line",stack:"总量",areaStyle:{opacity:.20},showSymbol:false,data:quarters.map(q=>asset.find((x:any)=>x.quarter===q)?.equity||0),lineStyle:{width:1.6,color:"#315c94"},itemStyle:{color:"#315c94"}},{name:"债券固收",type:"line",stack:"总量",areaStyle:{opacity:.15},showSymbol:false,data:quarters.map(q=>asset.find((x:any)=>x.quarter===q)?.fixed_income||0),lineStyle:{width:1.4,color:"#7e8ea3"},itemStyle:{color:"#7e8ea3"}},{name:"现金货币",type:"line",stack:"总量",areaStyle:{opacity:.10},showSymbol:false,data:quarters.map(q=>asset.find((x:any)=>x.quarter===q)?.cash||0),lineStyle:{width:1.3,color:"#c4cbd4"},itemStyle:{color:"#c4cbd4"}}]}}/>:<EmptyState title="暂无资产配置数据" body="请先在数据中心更新市场报告。"/>}</Panel><Panel title="行业配置" meta={<span>最新报告期</span>}>{sectorLatest.length?<Chart height={340} option={{tooltip:{trigger:"axis",axisPointer:{type:"shadow"}},grid:categoryGrid(18,18,16,22),xAxis:{type:"value",axisLabel:{formatter:"{value}%",color:"#98a2b3"},splitLine:{lineStyle:{color:"#eef0f3"}}},yAxis:{type:"category",data:sectorLatest.map((x:any)=>x.sector).reverse(),axisLabel:{color:"#475467",width:180,overflow:"truncate"},axisLine:{show:false},axisTick:{show:false}},series:[{type:"bar",data:sectorLatest.map((x:any)=>x.weight_pct).reverse(),barWidth:10,itemStyle:{color:"#4f7f70",borderRadius:[0,3,3,0]}}]}}/>:<EmptyState title="暂无行业配置数据" body="当前数据源没有可用行业配置。"/>}</Panel></div>
  <div className="grid two-equal"><Panel title="机构覆盖变化" meta={<span>季度增减</span>}>{movers.length?<Chart height={410} option={{tooltip:{trigger:"axis",axisPointer:{type:"shadow"}},grid:categoryGrid(18,18,16,24),xAxis:{type:"value",splitLine:{lineStyle:{color:"#eef0f3"}},axisLabel:{color:"#98a2b3"}},yAxis:{type:"category",data:movers.map((x:any)=>x.stock_name),axisLabel:{color:"#475467"},axisLine:{show:false},axisTick:{show:false}},series:[{type:"bar",data:movers.map((x:any)=>({value:x.delta,itemStyle:{color:x.delta>=0?"#2f8f70":"#c95b66"}})),barWidth:9}]}}/>:<EmptyState title="暂无变化数据" body="至少需要两个市场报告期。"/>}</Panel><Panel title="机构持有最集中" meta={<span>按覆盖基金数排序</span>}><DataTable data={data.crowded||[]} columns={cols} maxHeight={410}/></Panel></div></>;
}
