import { useEffect,useMemo,useState } from "react";
import type { ColumnDef } from "@tanstack/react-table";
import { ExternalLink,X } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { api } from "../lib/api";
import { useAppStore } from "../store/useAppStore";
import { PageHeader } from "../components/PageHeader";
import { MetricStrip } from "../components/MetricStrip";
import { Panel } from "../components/Panel";
import { Chart } from "../components/Chart";
import { DataTable } from "../components/DataTable";
import { DataContext } from "../components/DataContext";
import { Loading,ErrorState,EmptyState } from "../components/Loading";
import { sortPeriods } from "../lib/chartUtils";
import { filterConsensus } from "../lib/research";
import { formatNumber,formatSigned } from "../lib/format";
import type { ConsensusRow,SecurityDetailResponse,SmartMoneyResponse } from "../types";

const levels=['全部','高','中','低'];
const trends=['全部','新形成','持续增强','增强','稳定','弱化','退潮'];
const tone:Record<string,string>={新形成:'up',持续增强:'up',增强:'up',稳定:'flat',弱化:'down',退潮:'down'};

export function SmartMoneyPage(){
 const navigate=useNavigate();const mode=useAppStore(s=>s.mode);
 const[data,setData]=useState<SmartMoneyResponse|null>(null);const[refreshTick,setRefreshTick]=useState(0);const[period,setPeriod]=useState('');const[compare,setCompare]=useState('');const[windowSize,setWindowSize]=useState(8);const[level,setLevel]=useState('全部');const[trend,setTrend]=useState('全部');const[error,setError]=useState('');const[loading,setLoading]=useState(false);const[historyRows,setHistoryRows]=useState<any[]>([]);const[historyLoading,setHistoryLoading]=useState(false);const[historyError,setHistoryError]=useState('');const[detail,setDetail]=useState<SecurityDetailResponse|null>(null);const[detailLoading,setDetailLoading]=useState(false);
 useEffect(()=>{let alive=true;setLoading(true);setError('');api.smartMoney(mode,period,compare).then(x=>{if(!alive)return;setData(x);if(x.selected_period&&x.selected_period!==period)setPeriod(String(x.selected_period));if((x.compare_period||'')!==compare)setCompare(String(x.compare_period||''))}).catch((e:any)=>alive&&setError(e?.message||"请求未完成，请稍后重试")).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[mode,period,compare,refreshTick]);
 useEffect(()=>{if(!data?.data_context?.progressive_pending)return;const t=window.setTimeout(()=>{api.invalidateCache('/api/smart-money?');setRefreshTick(x=>x+1)},4500);return()=>window.clearTimeout(t)},[data?.data_context?.progressive_pending,mode,period,compare]);
 const periods=data?.periods||[];const selected=data?.selected_period||period;const selectedIndex=periods.indexOf(String(selected));const compareOptions=selectedIndex>0?periods.slice(0,selectedIndex):[];const lifecycle=data?.lifecycle||[];const filtered=useMemo(()=>filterConsensus(lifecycle,level,trend),[lifecycle,level,trend]);
 const historyCodes=useMemo(()=>lifecycle.filter(x=>Number(x.fund_count)>0).slice(0,12).map(x=>String(x.stock_code)),[lifecycle]);const historyCodeKey=historyCodes.join(',');
 useEffect(()=>{if(data?.data_context?.progressive_pending||!selected||!historyCodes.length){setHistoryRows([]);setHistoryError('');return}let alive=true;setHistoryLoading(true);setHistoryError('');api.smartMoneyHistory(mode,String(selected),historyCodes,windowSize).then(x=>{if(alive)setHistoryRows(x?.coverage_history||[])}).catch((e:any)=>{if(alive)setHistoryError(e?.message||'历史序列载入较慢')}).finally(()=>alive&&setHistoryLoading(false));return()=>{alive=false}},[mode,selected,windowSize,historyCodeKey,data?.data_context?.progressive_pending]);
 const levelCounts=useMemo(()=>Object.fromEntries(levels.slice(1).map(k=>[k,lifecycle.filter(x=>x.consensus_level===k).length])),[lifecycle]);const trendCounts=useMemo(()=>Object.fromEntries(trends.slice(1).map(k=>[k,lifecycle.filter(x=>x.consensus_trend===k).length])),[lifecycle]);
 const openSecurity=async(row:ConsensusRow)=>{setDetailLoading(true);try{setDetail(await api.securityDetail(mode,row.stock_code,String(selected||'')))}catch{setDetail(null)}finally{setDetailLoading(false)}};
 const coverageHistory=useMemo(()=>{const rows=historyRows||[];const names:string[]=[];for(const x of lifecycle.slice(0,6)){if(!names.includes(x.stock_name))names.push(x.stock_name)}const histPeriods=sortPeriods(rows.map(x=>String(x.quarter||''))).filter(p=>periods.indexOf(p)<=selectedIndex).slice(-windowSize);const series=names.map(name=>({name,type:'line',showSymbol:false,smooth:.18,data:histPeriods.map(p=>{const r=rows.find(x=>x.quarter===p&&x.stock_name===name);return r?.coverage_rate_pct??null}),lineStyle:{width:2},connectNulls:false}));return{periods:histPeriods,series}},[historyRows,lifecycle,selected,windowSize]);
 const sectorHeat=useMemo(()=>{const h=data?.sector_history||[];const allPeriods=sortPeriods(h.map((x:any)=>String(x.quarter||'')));const usable=allPeriods.filter((p:string)=>!selected||periods.indexOf(p)<=selectedIndex).slice(-windowSize);const totals=new Map<string,number>();h.filter((x:any)=>usable.includes(String(x.quarter))).forEach((x:any)=>totals.set(x.sector,(totals.get(x.sector)||0)+Number(x.weight_pct||0)));const sectors=[...totals].sort((a,b)=>b[1]-a[1]).slice(0,12).map(x=>x[0]);const matrix:any[]=[];sectors.forEach((s,yi)=>usable.forEach((p,xi)=>{const r=h.find((x:any)=>x.quarter===p&&x.sector===s);matrix.push([xi,yi,Number(r?.weight_pct||0)])}));return{periods:usable,sectors,matrix}},[data,selected,windowSize]);
 const sectorRows=useMemo(()=>[...(data?.sector_change||[])].sort((a:any,b:any)=>Math.abs(Number(b.delta||0))-Math.abs(Number(a.delta||0))).slice(0,18).sort((a:any,b:any)=>Number(a.delta)-Number(b.delta)),[data]);const mapRows=useMemo(()=>lifecycle.filter(x=>Number(x.fund_count)>0).slice().sort((a,b)=>Number(b.coverage_rate_pct)-Number(a.coverage_rate_pct)).slice(0,100),[lifecycle]);
 const cols:ColumnDef<ConsensusRow>[]=[
  {accessorKey:'stock_name',header:'证券',cell:({row,getValue})=><div className="security-cell"><span className="security-dot"/><div><b>{String(getValue())}</b><small>{row.original.stock_code}</small></div></div>},
  {accessorKey:'sector',header:'行业'},{accessorKey:'coverage_rate_pct',header:'当前覆盖率',cell:({getValue})=><span className="num strong">{formatNumber(getValue())}%</span>},{accessorKey:'fund_count',header:'可比基金数',cell:({getValue})=><span className="num">{Number(getValue()).toLocaleString()}</span>},
  {accessorKey:'coverage_delta_pp',header:'覆盖率变化',cell:({getValue})=>{const v=Number(getValue()||0);return <span className={`num ${v>0?'positive':v<0?'negative':''}`}>{formatSigned(v,2,' pp')}</span>}},
  {accessorKey:'change_per_quarter',header:'每季基金数变化',cell:({getValue})=><span className="num">{formatSigned(getValue(),2)}</span>},
  {accessorKey:'acceleration',header:'变化加速度',cell:({getValue})=>{const raw=getValue();if(raw==null)return <span className="muted">—</span>;const v=Number(raw);return <span className={`num ${v>0?'positive':v<0?'negative':''}`}>{formatSigned(v,2,' pp')}</span>}},
  {accessorKey:'consensus_level',header:'共识水平',cell:({getValue})=><span className="activity-pill info">{String(getValue())}</span>},{accessorKey:'consensus_trend',header:'共识趋势',cell:({getValue})=>{const v=String(getValue());return <span className={`activity-pill ${tone[v]||'flat'}`}>{v}</span>}},
 ];
 if(error&&!data)return <><PageHeader eyebrow="机构洞察" title="机构共识"/><div className="smart-money-load-error"><ErrorState compact message={error} onRetry={()=>{setError('');api.invalidateCache('/api/smart-money?');setRefreshTick(x=>x+1)}}/></div></>;if(!data)return <Loading label="正在整理机构共识"/>;if(!periods.length)return <><PageHeader eyebrow="机构洞察" title="机构共识"/><EmptyState title="暂无可比较的机构持仓" body="请先在数据中心采集基金季度持仓。"/></>;
 return <>
  <PageHeader eyebrow="机构洞察" title="机构共识"/>
  <DataContext period={String(selected||'')} basis={data.data_context?.basis_label} sampleFunds={data.data_context?.sample_funds} updatedAt={data.data_context?.updated_at} note={data.data_context?.note}/>
  {data.data_context?.progressive_pending&&<div className="research-refresh-indicator"><span/>正在后台整理可比基金样本，当前先展示市场快照，完成后会自动刷新。</div>}
  <div className="consensus-toolbar"><div className="consensus-periods"><label><span>当前报告期</span><select value={String(selected||'')} onChange={e=>{setPeriod(e.target.value);setCompare('');setLevel('全部');setTrend('全部')}}>{periods.map(p=><option key={p} value={p}>{p}</option>)}</select></label><span className="compare-arrow">对比</span><label><span>基准报告期</span><select value={compare} disabled={!compareOptions.length} onChange={e=>{setCompare(e.target.value);setLevel('全部');setTrend('全部')}}>{compareOptions.map(p=><option key={p} value={p}>{p}</option>)}</select></label></div><div className="consensus-window"><span>历史窗口</span>{[4,8,12,20].map(n=><button key={n} className={windowSize===n?'active':''} onClick={()=>setWindowSize(n)}>最近 {n} 季</button>)}</div></div>
  {loading&&<div className="soft-loading-bar" aria-label="正在刷新"/>}
  <MetricStrip items={[{label:'当前覆盖证券',value:(data.summary?.security_count||0).toLocaleString(),sub:String(selected||'')},{label:'共识增强',value:(data.summary?.strengthening_count||0).toLocaleString(),sub:`较 ${compare||'—'} 增强`},{label:'共识减弱',value:(data.summary?.weakening_count||0).toLocaleString(),sub:`较 ${compare||'—'} 弱化`},{label:'高共识证券',value:(data.summary?.high_consensus_count||0).toLocaleString(),sub:`覆盖率 P75 ${formatNumber(data.summary?.p75_coverage_rate_pct)}%`}]}/>
  <div className="grid two-equal consensus-primary-grid"><Panel title="机构共识地图" meta={<span>{compare||'—'} → {selected}</span>}>{mapRows.length?<Chart height={410} option={{tooltip:{confine:true,formatter:(p:any)=>`${p.data.name}<br/>当前覆盖率：${formatNumber(p.data.rate)}%<br/>覆盖率变化：${formatSigned(p.data.delta,2,' pp')}<br/>可比基金：${p.data.count}<br/>${p.data.level}共识 · ${p.data.trend}`},grid:{left:30,right:26,top:30,bottom:56,containLabel:true},xAxis:{type:'value',name:'覆盖率变化 pp',nameLocation:'middle',nameGap:34,nameTextStyle:{color:'#98a2b3',fontSize:11},splitLine:{lineStyle:{color:'#eef0f3'}},axisLabel:{color:'#98a2b3',formatter:(v:number)=>Number(v).toFixed(2)}},yAxis:{type:'value',name:'当前覆盖率 %',nameLocation:'middle',nameGap:50,nameTextStyle:{color:'#98a2b3',fontSize:11},splitLine:{lineStyle:{color:'#eef0f3'}},axisLabel:{color:'#98a2b3',formatter:(v:number)=>Number(v).toFixed(2)}},series:trends.slice(1).map(st=>({name:st,type:'scatter',data:mapRows.filter(x=>x.consensus_trend===st).map(x=>({name:x.stock_name,value:[x.coverage_delta_pp,x.coverage_rate_pct],rate:x.coverage_rate_pct,delta:x.coverage_delta_pp,count:x.fund_count,level:x.consensus_level,trend:x.consensus_trend,code:x.stock_code,symbolSize:Math.max(9,Math.min(30,8+Math.sqrt(Number(x.fund_count||0))*1.05))})),itemStyle:{opacity:.72}}))}} onEvents={{click:(p:any)=>{const row=lifecycle.find(x=>x.stock_code===p?.data?.code);if(row)openSecurity(row)}}}/>:<EmptyState title="暂无可比较证券" body="所选报告期没有形成有效覆盖变化。"/>}</Panel><Panel title="共识演化" meta={<span>覆盖率 · 最近 {coverageHistory.periods.length||Math.min(windowSize,periods.length)} 季</span>}>{coverageHistory.series.length?<Chart height={410} option={{tooltip:{trigger:'axis',confine:true},legend:{top:2,type:'scroll',textStyle:{fontSize:10,color:'#667085'}},grid:{left:24,right:20,top:44,bottom:34,containLabel:true},xAxis:{type:'category',data:coverageHistory.periods,axisLabel:{color:'#98a2b3',hideOverlap:true}},yAxis:{type:'value',name:'覆盖率 %',nameLocation:'middle',nameGap:46,nameTextStyle:{color:'#98a2b3',fontSize:11},splitLine:{lineStyle:{color:'#eef0f3'}},axisLabel:{color:'#98a2b3',formatter:(v:number)=>Number(v).toFixed(2)}},series:coverageHistory.series}}/>:historyLoading?<Loading compact label="核心共识已就绪，正在补充历史轨迹"/>:historyError?<EmptyState compact title="历史轨迹暂未完成" body="核心共识与当前期比较已可使用，可稍后切换窗口重试。"/>:<EmptyState title="历史深度不足" body="当前证券缺少连续报告期覆盖数据。"/>}</Panel></div>
  <div className="grid two-equal"><Panel title="行业配置变化" meta={<span>{compare||'—'} → {selected} · pp</span>}>{sectorRows.length?<Chart height={420} option={{tooltip:{trigger:'axis',axisPointer:{type:'shadow'},confine:true,formatter:(items:any[])=>{const p=items?.[0];return p?`${p.name}<br/>变化：${formatSigned(p.value,2,' pp')}`:''}},grid:{left:22,right:28,top:18,bottom:26,containLabel:true},xAxis:{type:'value',splitLine:{lineStyle:{color:'#eef0f3'}},axisLabel:{color:'#98a2b3',formatter:(v:number)=>Number(v).toFixed(2)}},yAxis:{type:'category',data:sectorRows.map((x:any)=>x.sector),axisLabel:{color:'#475467',width:150,overflow:'truncate'},axisLine:{show:false},axisTick:{show:false}},series:[{type:'bar',barWidth:10,data:sectorRows.map((x:any)=>({value:Number(x.delta||0),itemStyle:{color:Number(x.delta)>=0?'#315c94':'#c95b66',borderRadius:Number(x.delta)>=0?[0,4,4,0]:[4,0,0,4]}}))}]}}/>:<EmptyState title="暂无行业变化" body="两个报告期之间没有可比较的行业配置数据。"/>}</Panel><Panel title="行业参与度历史" meta={<span>最近 {sectorHeat.periods.length} 季</span>}>{sectorHeat.matrix.length?<Chart height={420} option={{tooltip:{position:'top',confine:true,formatter:(p:any)=>`${sectorHeat.sectors[p.value[1]]}<br/>${sectorHeat.periods[p.value[0]]}<br/>配置权重：${formatNumber(p.value[2])}%`},grid:{left:18,right:18,top:14,bottom:54,containLabel:true},xAxis:{type:'category',data:sectorHeat.periods,axisLabel:{color:'#98a2b3'}},yAxis:{type:'category',data:sectorHeat.sectors,axisLabel:{color:'#475467',width:150,overflow:'truncate'},axisLine:{show:false},axisTick:{show:false}},visualMap:{min:0,max:Math.max(10,...sectorHeat.matrix.map(x=>x[2])),orient:'horizontal',left:'center',bottom:0,textStyle:{color:'#98a2b3'},inRange:{color:['#f4f7f6','#dceae5','#9fc9b8','#397b64']}},series:[{type:'heatmap',data:sectorHeat.matrix,itemStyle:{borderWidth:2,borderColor:'#fff'}}]}}/>:<EmptyState title="暂无行业历史" body="当前没有可用的行业配置历史。"/>}</Panel></div>
  <Panel title="证券共识观察" meta={<span>{filtered.length.toLocaleString()} 条 · {selected}</span>}><div className="consensus-filter-groups"><div className="consensus-state-filter"><span>水平</span>{levels.map(k=><button key={k} className={level===k?'active':''} onClick={()=>setLevel(k)}>{k}{k!=='全部'&&levelCounts[k]!=null?<small>{levelCounts[k]}</small>:null}</button>)}</div><div className="consensus-state-filter"><span>趋势</span>{trends.map(k=><button key={k} className={trend===k?'active':''} onClick={()=>setTrend(k)}>{k}{k!=='全部'&&trendCounts[k]!=null?<small>{trendCounts[k]}</small>:null}</button>)}</div></div>{filtered.length?<DataTable data={filtered} columns={cols} maxHeight={590} onRowClick={openSecurity}/>:<EmptyState title="当前筛选没有证券" body="可以切换共识水平、趋势或报告期。"/>}</Panel>
  <div className="method-note">共识水平基于当前可比基金 cohort 的覆盖率分位；共识趋势基于同一 cohort 的覆盖率变化。跨期加速度仅在前后区间长度一致且三期基金样本一致时展示。</div>
  {(detail||detailLoading)&&<div className="explorer-drawer-backdrop" onMouseDown={()=>!detailLoading&&setDetail(null)}><aside className="explorer-drawer" onMouseDown={e=>e.stopPropagation()}>{detailLoading?<Loading label="正在整理机构持仓轨迹"/>:detail&&<><div className="drawer-head"><div><small>{detail.security.stock_code}</small><h2>{detail.security.stock_name}</h2><span>{detail.security.sector||'未分类'}</span></div><div className="drawer-actions"><button onClick={()=>setDetail(null)}><X size={18}/></button></div></div><DataContext period={detail.selected_period} basis={detail.data_context?.basis_label} sampleFunds={detail.data_context?.sample_funds} updatedAt={detail.data_context?.updated_at} note={detail.data_context?.note}/><Panel title="机构覆盖轨迹"><Chart height={250} option={{tooltip:{trigger:'axis',confine:true},grid:{left:18,right:18,top:18,bottom:34,containLabel:true},xAxis:{type:'category',data:detail.history.map(x=>x.period)},yAxis:{type:'value',axisLabel:{formatter:(v:number)=>`${Number(v).toFixed(2)}%`},splitLine:{lineStyle:{color:'#eef0f3'}}},series:[{type:'line',showSymbol:false,data:detail.history.map(x=>x.coverage_rate_pct),lineStyle:{width:2}}]}}/></Panel><div className="drawer-kpis"><div><span>当前覆盖率</span><b>{formatNumber(detail.history.find(x=>x.period===detail.selected_period)?.coverage_rate_pct)}%</b></div><div><span>新进入前十</span><b className="positive">{detail.entrants.length}</b></div><div><span>退出前十</span><b className="negative">{detail.exits.length}</b></div></div><div className="drawer-section-head"><b>基金行为明细</b></div><div className="drawer-change-list">{detail.fund_changes.slice(0,30).map((x:any)=><button key={x.fund_code} onClick={()=>navigate(`/funds?code=${encodeURIComponent(x.fund_code)}`)}><div><b>{x.fund_name}</b><small>{x.fund_code}</small></div><span className="num">{x.weight_old==null?'—':`${formatNumber(x.weight_old)}%`} → {x.weight_new==null?'—':`${formatNumber(x.weight_new)}%`}</span><strong className={x.delta>0?'positive':x.delta<0?'negative':''}>{formatSigned(x.delta)}</strong><ExternalLink size={13}/></button>)}</div></>}</aside></div>}
 </>;
}
